import Decimal from 'decimal.js';
import type {Instrument,MetrologicalEvent,Role} from './types';
import {currentProcedureInstrumentErrors,daysUntil,decimal,emptyEvent} from './metrology';
export type RegistrationState='rascunho'|'aguardando aprovação'|'aprovado'|'devolvido';
export interface SimpleCertificate extends Pick<MetrologicalEvent,'date'|'nextDate'|'laboratory'|'laboratoryAccredited'|'certificateNumber'|'toleranceReferenceDocument'|'processTolerance'|'measurementUncertainty'|'measurementError'|'resultBasis'|'calibrationAccepted'|'acceptedWithRestriction'|'decision'|'attachmentPath'> {standardsValidation:string;attachmentName:string}
export interface SimpleRegistration {id:string;instrumentId:string;companyId:string;version:number;state:RegistrationState;instrument:Instrument;certificate:SimpleCertificate;createdBy:string;submittedAt:string;reviewedBy:string;reviewedName?:string;reviewedAt:string;reviewNotes:string;quantitative:{status:string;total:string;operator:string};baseUpdatedAt?:string;updatedAt?:string}
export interface Member {userId:string;email:string;role:Role;companyId:string|null;active:boolean}
export const roleLabels:Record<string,string>={owner:'Proprietário',quality_admin:'Responsável',analyst:'Cadastro',viewer:'Consulta',inspector:'Consulta',contractor:'Consulta'};
export function newCertificate(instrumentId:string):SimpleCertificate {return {...emptyEvent(instrumentId),standardsValidation:'',attachmentName:''};}
export function evaluateSimple(c:SimpleCertificate){const e=decimal(c.measurementError),u=decimal(c.measurementUncertainty),t=decimal(c.processTolerance);if(!e||!u||!t||!t.gt(0)||!c.resultBasis)return {status:'pendente',total:'',operator:'<='};const D=Decimal.clone({precision:Math.max(40,c.measurementError.length+c.measurementUncertainty.length+c.processTolerance.length+8)});const total=new D(e.toFixed()).abs().plus(new D(u.toFixed()).abs());return {status:total.lte(t.toFixed())?'conforme':'não conforme',total:total.toFixed(),operator:'<='};}
export function simpleErrors(i:Instrument,c:SimpleCertificate){const errors=currentProcedureInstrumentErrors(i);for(const [key,label] of [['date','Data da calibração'],['nextDate','Validade / vencimento'],['laboratory','Entidade calibradora'],['certificateNumber','Número do certificado'],['toleranceReferenceDocument','Documento de referência da tolerância'],['attachmentPath','Anexo do certificado']] as const)if(!c[key]?.trim())errors.push(`Informe ${label}.`);if(c.date&&(!validDay(c.date)||!validDay(c.nextDate)||c.nextDate<=c.date))errors.push('O vencimento deve ser uma data posterior à calibração.');if(evaluateSimple(c).status==='pendente')errors.push('Preencha erro, incerteza, tolerância positiva e % ou unidade.');for(const key of ['laboratoryAccredited','calibrationAccepted','acceptedWithRestriction'] as const)if(!['sim','não'].includes(c[key]))errors.push('Preencha as respostas de laboratório, aceitação e restrição.');if(!c.decision)errors.push('Informe a situação do equipamento.');return errors;}
function validDay(v:string){return /^\d{4}-\d{2}-\d{2}$/.test(v)&&!Number.isNaN(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v;}
export function monitoringStatus(i:Instrument,window:number,today?:string){if(!i.lastControl)return 'aguardando aprovação';const days=daysUntil(i.nextControl,today);return days===null?'sem vencimento':days<0?'vencido':days<=window?'próximo do vencimento':'em dia';}
export function suggestExpiry(date:string,months:number|null){if(!validDay(date)||!months)return '';const [y,m,d]=date.split('-').map(Number);const end=new Date(Date.UTC(y,m-1+months+1,0));return new Date(Date.UTC(end.getUTCFullYear(),end.getUTCMonth(),Math.min(d,end.getUTCDate()))).toISOString().slice(0,10);}
