import {chromium} from 'playwright';
import {expect} from '@playwright/test';
import {spawn} from 'node:child_process';
import {mkdirSync,readFileSync,writeFileSync} from 'node:fs';
import * as XLSX from 'xlsx';
mkdirSync('test-results',{recursive:true});
const server=spawn(process.execPath,['node_modules/vite/bin/vite.js','--host','127.0.0.1','--port','5173','--strictPort'],{stdio:['ignore','pipe','pipe']});
let browser;const checks=[];const errors=[];
try{
 let serverOutput='';let serverExit=null;
 server.stdout.on('data',b=>{serverOutput+=b.toString();});server.stderr.on('data',b=>{serverOutput+=b.toString();});
 server.on('exit',(code,signal)=>{serverExit=`code=${code}, signal=${signal}`;});server.on('error',error=>{serverExit=error.message;});
 const startupDeadline=Date.now()+15000;let ready=false;
 while(Date.now()<startupDeadline){
  if(serverExit!==null)throw new Error(`Dev server exited (${serverExit})\n${serverOutput}`);
  try{const response=await fetch('http://127.0.0.1:5173',{signal:AbortSignal.timeout(1000)});if(response.ok){ready=true;break;}}catch{}
  await new Promise(resolve=>setTimeout(resolve,100));
 }
 if(!ready)throw new Error(`Dev server HTTP readiness timeout\n${serverOutput}`);
 browser=await chromium.launch({headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--no-zygote','--single-process']});
 const page=await browser.newPage({viewport:{width:1440,height:1000},acceptDownloads:true});page.setDefaultTimeout(8000);page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 await page.goto('http://127.0.0.1:5173');await expect(page.getByRole('heading',{name:'Metrikon'})).toBeVisible();await expect(page.locator('vite-error-overlay')).toHaveCount(0);await expect(page).toHaveTitle('Metrikon');await expect(page.getByAltText('Logo Metrikon')).toBeVisible();await expect.poll(()=>page.getByAltText('Logo Metrikon').evaluate(img=>img.complete&&img.naturalWidth===1254)).toBe(true);await page.screenshot({path:'test-results/login-metrikon.png',fullPage:true});const manifest=await (await page.request.get('http://127.0.0.1:5173/manifest.webmanifest')).json();expect(manifest.name).toBe('Metrikon');for(const icon of manifest.icons)expect((await page.request.get(new URL(icon.src,'http://127.0.0.1:5173').href)).ok()).toBe(true);expect((await page.request.get('http://127.0.0.1:5173/favicon.ico')).ok()).toBe(true);checks.push('Metrikon: título, logo original, manifesto e ícones carregados');
 await page.getByRole('button',{name:/Explorar demonstração/}).click();await expect(page.getByRole('heading',{name:'Visão geral',exact:true})).toBeVisible();await page.screenshot({path:'test-results/dashboard-1440.png',fullPage:true});checks.push('Dashboard desktop e dados fictícios');
 const clickNav=async name=>page.getByRole('navigation',{name:'Menu principal'}).getByRole('button',{name,exact:true}).click();
 for(const name of ['Instrumentos','Controles metrológicos','Pendências','Empresas','Cadastros auxiliares','Laboratórios e padrões','Importar LI','Histórico de auditoria','Configurações e fases','Visão geral']){await clickNav(name);await expect(page.locator('#main h1')).toHaveText(name);}
 checks.push('Todos os itens do menu navegam sem erro');
 await clickNav('Laboratórios e padrões');await page.getByRole('button',{name:'Novo laboratório',exact:true}).click();let traceDialog=page.getByRole('dialog');
 await traceDialog.getByLabel('Empresa do vínculo *',{exact:true}).selectOption({label:'CONSAG'});await traceDialog.getByLabel('Nome do laboratório *',{exact:true}).fill('Laboratório QA');await traceDialog.getByLabel('Acreditação informada',{exact:true}).selectOption('sim');await traceDialog.getByLabel('Referência da acreditação',{exact:true}).fill('ACR-QA-001');await traceDialog.getByLabel('Escopo do laboratório',{exact:true}).fill('Comprimento');await traceDialog.getByLabel('Início da acreditação',{exact:true}).fill('2026-01-01');await traceDialog.getByLabel('Fim da acreditação',{exact:true}).fill('2026-12-31');await traceDialog.getByRole('button',{name:'Salvar laboratório',exact:true}).click();await expect(page.getByRole('heading',{name:'Laboratório QA',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Padrões',exact:true}).click();await page.getByRole('button',{name:'Novo padrão',exact:true}).click();traceDialog=page.getByRole('dialog');await traceDialog.getByLabel('Empresa do vínculo *',{exact:true}).selectOption({label:'CONSAG'});await traceDialog.getByLabel('Nome do padrão *',{exact:true}).fill('Bloco padrão QA');await traceDialog.getByLabel('Série / identificação do padrão *',{exact:true}).fill('PAD-QA-001');await traceDialog.getByLabel('Grandeza do padrão',{exact:true}).fill('Comprimento');await traceDialog.getByLabel('Faixa do padrão',{exact:true}).fill('0 A 45');await traceDialog.getByLabel('Unidade do padrão',{exact:true}).fill('mm');await traceDialog.getByRole('button',{name:'Salvar padrão',exact:true}).click();await page.getByRole('button',{name:'Certificados de PAD-QA-001',exact:true}).click();await page.getByRole('button',{name:'Novo certificado do padrão',exact:true}).click();traceDialog=page.getByRole('dialog');await traceDialog.getByLabel('Número do certificado do padrão *',{exact:true}).fill('PAD-QA-2026');await traceDialog.getByLabel('Entidade emissora do padrão *',{exact:true}).fill('Emissor QA');await traceDialog.getByLabel('Vincular laboratório emissor',{exact:true}).selectOption({label:'Laboratório QA'});await traceDialog.getByLabel('Data da calibração do padrão *',{exact:true}).fill('2026-01-01');await traceDialog.getByLabel('Validade do certificado do padrão',{exact:true}).fill('2026-12-31');await traceDialog.getByLabel('Escopo do certificado do padrão',{exact:true}).fill('Comprimento 0 A 45 mm');await traceDialog.getByLabel('Evidência de rastreabilidade do padrão',{exact:true}).fill('Certificado rastreável QA');await traceDialog.getByLabel('Arquivo do certificado do padrão',{exact:true}).setInputFiles({name:'padrao-qa.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4\n%%EOF')});await traceDialog.getByRole('button',{name:'Registrar certificado do padrão',exact:true}).click();await expect(page.getByRole('heading',{name:'PAD-QA-2026 · versão 1',exact:true})).toBeVisible();await page.screenshot({path:'test-results/traceability-desktop.png',fullPage:true});checks.push('Fase 3: laboratório, padrão e certificado privado versionado');

 await clickNav('Instrumentos');await page.getByRole('button',{name:'Novo instrumento',exact:true}).click();let dialog=page.getByRole('dialog');
 await expect(dialog.getByText('Próxima sequência prevista: CE-5290.00-22313-856-C1O-843 • linha 850.',{exact:false})).toBeVisible();
 for(const removed of ['Código interno RHDD','Descrição','Tipo / família','Fabricante','TAG','Identificação interna','Patrimônio','Empresa proprietária','Empresa usuária','Área','Setor','Responsável','Tipo de controle','Observações'])await expect(dialog.getByLabel(removed,{exact:true})).toHaveCount(0);
 await dialog.getByLabel('Obra *',{exact:true}).fill('RHDD');
 await dialog.getByLabel('Equipamento crítico *',{exact:true}).fill('HI-LO (ESCALA)');
 await dialog.getByLabel('Código de série / identificação *',{exact:true}).fill('QA-SERIE-007');
 await dialog.getByLabel('Modelo *',{exact:true}).fill('WG-601');
 await dialog.getByLabel('Local de uso *',{exact:true}).fill('FRENTE DE SERVIÇO');
 await dialog.getByLabel('Área/Setor responsável pela calibração do equipamento *',{exact:true}).fill('QUALIDADE');
 await dialog.getByLabel('Processo *',{exact:true}).fill('QUALIDADE');
 await dialog.getByLabel('Faixa de medição *',{exact:true}).fill('0 A 45 MM');
 await dialog.getByLabel('Faixa de utilização *',{exact:true}).fill('0 A 45 MM');
 await dialog.getByLabel('Valor da divisão de verificação do equipamento *',{exact:true}).fill('0,1 MM');
 await dialog.getByLabel('Intervalo de calibrações (em meses) *',{exact:true}).fill('12');
 await dialog.getByLabel('Status do cadastro *',{exact:true}).selectOption('inativo');
 await dialog.getByRole('button',{name:'Salvar instrumento',exact:true}).click();
 await expect(page.getByRole('button',{name:'CE-5290.00-22313-856-C1O-843',exact:true})).toBeVisible();
 checks.push('Cadastro do instrumento contém somente os campos da ficha de referência e recebe LI automática');
 await page.getByLabel('Pesquisa global').fill('QA-SERIE-007');await expect(page.locator('.instrument-table tbody tr')).toHaveCount(1);await page.screenshot({path:'test-results/instruments-filtered-1440.png',fullPage:true});
 const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Exportar Excel',exact:true}).click();const download=await downloadPromise;await download.saveAs('test-results/Instrumentos_QA.xlsx');const book=XLSX.read(readFileSync('test-results/Instrumentos_QA.xlsx'),{type:'buffer'});const rows=XLSX.utils.sheet_to_json(book.Sheets[book.SheetNames[0]]);if(rows.length!==1||rows[0]['Número LI / N-1710']!=='CE-5290.00-22313-856-C1O-843'||rows[0]['Equipamento crítico']!=='HI-LO (ESCALA)')throw new Error('Exportação não respeitou filtro/cadastro de referência');checks.push('Busca por série e exportação Excel filtrada');
 await page.getByRole('button',{name:'CE-5290.00-22313-856-C1O-843',exact:true}).click();dialog=page.getByRole('dialog');await dialog.getByRole('button',{name:'Registrar controle',exact:true}).click();dialog=page.getByRole('dialog');
 await dialog.getByLabel('Data da calibração',{exact:true}).fill('2026-10-02');await dialog.getByText('Vincular laboratório e padrões desta calibração',{exact:true}).click();await dialog.getByLabel('Laboratório cadastrado para este evento',{exact:true}).selectOption({label:'Laboratório QA'});await dialog.getByLabel(/Bloco padrão QA · PAD-QA-001 · PAD-QA-2026/).check();await dialog.getByLabel('Uso do padrão PAD-QA-2026',{exact:true}).fill('Escala inferior');await expect(dialog.getByLabel('Laboratório acreditado?',{exact:true})).toHaveValue('');await dialog.getByLabel('Próxima data',{exact:true}).fill('2027-04-02');await dialog.getByLabel('Entidade calibradora',{exact:true}).fill('Laboratório QA');await dialog.getByLabel('Laboratório acreditado?',{exact:true}).selectOption('não');await dialog.getByRole('button',{name:'Continuar',exact:true}).click();
 await dialog.getByLabel('Número do certificado',{exact:true}).fill('QA-CERT-001');await dialog.getByLabel('Anexo do certificado / registro',{exact:true}).setInputFiles({name:'certificado-qa.xlsx',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',buffer:Buffer.from([0x50,0x4b,0x03,0x04,0x14,0x00,0x00,0x00])});await expect(dialog.getByText('Anexo vinculado ao evento',{exact:true})).toBeVisible();await dialog.getByLabel('Código de série / identificação',{exact:true}).fill('QA-SERIE-007');await dialog.getByRole('button',{name:'Continuar',exact:true}).click();
 for(const [label,value]of [['Documento de referência da tolerância','PR-QA-001'],['Tolerância do processo','0,50'],['Incerteza de medição','0,10'],['Erro de medição','0,40']])await dialog.getByLabel(label,{exact:true}).fill(value);await dialog.getByLabel('% ou unidade',{exact:true}).selectOption('unidade');
 await dialog.getByRole('button',{name:'Continuar',exact:true}).click();const selects=dialog.locator('.checklist select');for(let i=0;i<await selects.count();i++)await selects.nth(i).selectOption('conforme');await dialog.getByRole('button',{name:'Continuar',exact:true}).click();await expect(dialog.getByText('não conforme',{exact:true}).first()).toBeVisible();await page.screenshot({path:'test-results/quantitative-equality.png',fullPage:true});await dialog.getByRole('button',{name:'Continuar',exact:true}).click();await dialog.getByLabel('Calibração aceita?',{exact:true}).selectOption('não');await dialog.getByLabel('Aceito com restrição?',{exact:true}).selectOption('não');await dialog.getByLabel('Status do cadastro',{exact:true}).selectOption('inativo');await dialog.getByLabel('Situação do equipamento',{exact:true}).selectOption('liberado para uso');await dialog.getByLabel('Justificativa / conclusão humana',{exact:true}).fill('Análise humana de demonstração');await dialog.getByRole('button',{name:'Registrar decisão',exact:true}).click();await expect(dialog.getByRole('alert')).toContainText('quantitativa');checks.push('Upload XLSX 16 MB, preenchimento atual, checklist e igualdade rejeitada na liberação');
 for(let i=0;i<3;i++)await dialog.getByRole('button',{name:'Voltar',exact:true}).click();await dialog.getByLabel('Erro de medição',{exact:true}).fill('0,39');for(let i=0;i<3;i++)await dialog.getByRole('button',{name:'Continuar',exact:true}).click();await dialog.getByRole('button',{name:'Registrar decisão',exact:true}).click();dialog=page.getByRole('dialog');await expect(dialog.getByText('concluído',{exact:true})).toBeVisible();await expect(dialog.getByText('liberado para uso',{exact:true}).first()).toBeVisible();await expect(dialog.getByText('inativo',{exact:true}).first()).toBeVisible();await expect(dialog.getByText('Próximo controle',{exact:true})).toHaveCount(0);await expect(dialog.getByRole('heading',{name:'Rastreabilidade registrada na calibração',exact:true})).toBeVisible();await expect(dialog.locator('.trace-history')).toContainText('PAD-QA-2026');await expect(dialog.locator('.trace-history')).toContainText('válido na data');checks.push('Fase 3: vínculo histórico na data do evento e decisões independentes');await page.screenshot({path:'test-results/instrument-cycle.png',fullPage:true});await dialog.getByRole('button',{name:'Fechar',exact:true}).click();checks.push('Ciclo completo com aceitação/status/situação independentes e próxima data');
 await clickNav('Cadastros auxiliares');await page.getByRole('button',{name:'Novo item',exact:true}).click();dialog=page.getByRole('dialog');await dialog.getByLabel('Empresa proprietária',{exact:true}).selectOption({label:'CONSAG'});await dialog.getByLabel('Nome',{exact:true}).fill('Dimensional QA');await dialog.getByRole('button',{name:'Salvar item',exact:true}).click();await expect(page.getByText('Dimensional QA',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Editar item',exact:true}).click();dialog=page.getByRole('dialog');await dialog.getByLabel('Situação',{exact:true}).selectOption('inativo');await dialog.getByRole('button',{name:'Salvar item',exact:true}).click();await expect(page.locator('#main tbody')).toContainText('inativo');checks.push('Cadastro auxiliar por empresa e inativação sem exclusão');
 await clickNav('Instrumentos');await page.getByRole('button',{name:'CE-5290.00-22313-856-C1O-843',exact:true}).click();dialog=page.getByRole('dialog');await dialog.getByLabel('Anexar foto ou documento').setInputFiles({name:'manual-qa.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4\n%%EOF')});await expect(dialog.getByText('manual-qa.pdf',{exact:true})).toBeVisible();await dialog.getByRole('button',{name:'Fechar',exact:true}).click();await page.getByRole('button',{name:'CE-5290.00-22313-856-C1O-843',exact:true}).click();dialog=page.getByRole('dialog');await expect(dialog.getByText('manual-qa.pdf',{exact:true})).toBeVisible();await dialog.getByRole('button',{name:'Fechar',exact:true}).click();checks.push('Anexo cadastral validado e preservado ao reabrir a ficha');
 await clickNav('Importar LI');await page.getByLabel('Planilha LI',{exact:true}).setInputFiles({name:'LI-QA.csv',mimeType:'text/csv',buffer:Buffer.from('Código;Descrição;Número de série\r\nCE-5290.00-22313-856-C1O-100;Paquímetro importado;001234\r\nCE-5290.00-22313-856-C1O-843;Duplicado preservado;X\r\n;Descrição sem LI;Y')});await page.getByRole('button',{name:'Ler planilha',exact:true}).click();await expect(page.getByRole('heading',{name:'Correspondência das colunas'})).toBeVisible();await page.getByLabel('Empresa proprietária da importação').selectOption({label:'CONSAG'});await page.getByRole('button',{name:'Gerar prévia',exact:true}).click();await expect(page.getByText('1 duplicados',{exact:true})).toBeVisible();await expect(page.getByText('1 inválidos',{exact:true})).toBeVisible();const commit=page.getByRole('button',{name:'Confirmar importação de 1 instrumentos'});await expect(commit).toBeDisabled();await page.getByLabel(/Revisei o mapeamento/).check();await commit.click();await expect(page.getByText('Importação concluída: 1 criados, 0 duplicados preservados.',{exact:true})).toBeVisible();await page.screenshot({path:'test-results/li-import-result.png',fullPage:true});await page.getByLabel('Limpar pesquisa').click();await clickNav('Instrumentos');await page.getByLabel('Pesquisa global').fill('001234');await expect(page.locator('.instrument-table tbody tr')).toHaveCount(1);await page.getByRole('button',{name:'CE-5290.00-22313-856-C1O-100',exact:true}).click();dialog=page.getByRole('dialog');await expect(dialog.getByText('fora de uso',{exact:true})).toBeVisible();await expect(dialog.getByText('001234',{exact:true})).toBeVisible();await dialog.getByRole('button',{name:'Fechar',exact:true}).click();checks.push('LI em Worker: CSV UTF-8, zeros, mapeamento, duplicados, prévia e confirmação humana');
 await clickNav('Histórico de auditoria');await expect(page.locator('#main')).toContainText('Decisão metrológica');await expect(page.locator('#main')).toContainText('Cadastro de instrumento');
 await page.getByLabel('Limpar pesquisa').click();await clickNav('Visão geral');for(const width of [1366,1280]){await page.setViewportSize({width,height:900});await page.screenshot({path:`test-results/dashboard-${width}.png`,fullPage:true});const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);if(overflow)throw new Error(`Overflow desktop ${width}`);}checks.push('Layouts desktop 1440/1366/1280 sem overflow da página');
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'test-results/dashboard-390.png',fullPage:true});if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)){console.log(await page.evaluate(()=>[...document.querySelectorAll('body *')].filter(e=>e.getBoundingClientRect().right>innerWidth+1).map(e=>({tag:e.tagName,class:e.className,width:e.getBoundingClientRect().width,right:e.getBoundingClientRect().right})).slice(0,30)));throw new Error('Overflow mobile');}await page.getByRole('button',{name:'Abrir menu'}).click();await clickNav('Laboratórios e padrões');await page.getByRole('button',{name:'Padrões',exact:true}).click();await page.getByRole('button',{name:'Certificados de PAD-QA-001',exact:true}).click();await page.screenshot({path:'test-results/traceability-mobile.png',fullPage:true});if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw new Error('Overflow mobile laboratórios/padrões');checks.push('Fase 3: laboratório/padrão/certificado legíveis no mobile');await page.getByRole('button',{name:'Abrir menu'}).click();await clickNav('Configurações e fases');await expect(page.locator('#main h1')).toHaveText('Configurações e fases');checks.push('Consulta mobile 390px e navegação acessível');
 await page.getByRole('button',{name:'Sair',exact:true}).click();await page.getByRole('button',{name:/Explorar demonstração/}).click();await page.getByLabel('Pesquisa global').fill('QA-SERIE-007');await expect(page.locator('.instrument-table tbody tr')).toHaveCount(0);checks.push('Sessão demonstrativa reinicia sem persistir dados reais');
 if(errors.length)throw new Error(errors.join('\n'));writeFileSync('test-results/browser-report.json',JSON.stringify({passed:true,checks,pageErrors:errors},null,2));console.log(JSON.stringify({passed:true,checks,pageErrors:errors},null,2));
}catch(error){writeFileSync('test-results/browser-report.json',JSON.stringify({passed:false,checks,pageErrors:errors,error:String(error)},null,2));throw error;}finally{await browser?.close();server.kill();}
