import {chromium} from 'playwright';
import {expect} from '@playwright/test';
import {spawn} from 'node:child_process';
import {mkdirSync,readFileSync,writeFileSync} from 'node:fs';
import * as XLSX from 'xlsx';
mkdirSync('test-results',{recursive:true});
const server=spawn(process.execPath,['node_modules/vite/bin/vite.js','--host','127.0.0.1','--port','5173','--strictPort'],{stdio:['ignore','pipe','pipe']});
let browser;const checks=[];const errors=[];
try{
 let serverOutput='';let serverExit=null;
 server.stdout.on('data',b=>{serverOutput+=b.toString();});server.stderr.on('data',b=>{serverOutput+=b.toString();});
 server.on('exit',(code,signal)=>{serverExit=`code=${code}, signal=${signal}`;});server.on('error',error=>{serverExit=error.message;});
 const startupDeadline=Date.now()+15000;let ready=false;
 while(Date.now()<startupDeadline){
  if(serverExit!==null)throw new Error(`Dev server exited (${serverExit})\n${serverOutput}`);
  try{const response=await fetch('http://127.0.0.1:5173',{signal:AbortSignal.timeout(1000)});if(response.ok){ready=true;break;}}catch{}
  await new Promise(resolve=>setTimeout(resolve,100));
 }
 if(!ready)throw new Error(`Dev server HTTP readiness timeout\n${serverOutput}`);
 browser=await chromium.launch({headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--no-zygote','--single-process']});
 const page=await browser.newPage({viewport:{width:1440,height:1000},acceptDownloads:true});page.setDefaultTimeout(8000);page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 await page.goto('http://127.0.0.1:5173');await expect(page.getByRole('heading',{name:'Metrikon'})).toBeVisible();await expect(page.locator('vite-error-overlay')).toHaveCount(0);await expect(page).toHaveTitle('Metrikon');await expect(page.getByAltText('Logo Metrikon')).toBeVisible();await expect.poll(()=>page.getByAltText('Logo Metrikon').evaluate(img=>img.complete&&img.naturalWidth===1254)).toBe(true);await page.screenshot({path:'test-results/login-metrikon.png',fullPage:true});const manifest=await (await page.request.get('http://127.0.0.1:5173/manifest.webmanifest')).json();expect(manifest.name).toBe('Metrikon');for(const icon of manifest.icons)expect((await page.request.get(new URL(icon.src,'http://127.0.0.1:5173').href)).ok()).toBe(true);expect((await page.request.get('http://127.0.0.1:5173/favicon.ico')).ok()).toBe(true);checks.push('Metrikon: título, logo original, manifesto e ícones carregados');
 await page.getByRole('button',{name:/Explorar demonstração/}).click();await expect(page.getByRole('heading',{name:'Visão geral',exact:true})).toBeVisible();await page.screenshot({path:'test-results/dashboard-1440.png',fullPage:true});checks.push('Dashboard desktop e dados fictícios');
 const clickNav=async name=>page.getByRole('navigation',{name:'Menu principal'}).getByRole('button',{name,exact:true}).click();
 for(const name of ['Instrumentos','Controles metrológicos','Pendências','Empresas','Cadastros auxiliares','Importar LI','Histórico de auditoria','Configurações e fases','Visão geral']){await clickNav(name);await expect(page.locator('#main h1')).toHaveText(name);}
 checks.push('Todos os itens do menu navegam sem erro');
 await clickNav('Instrumentos');await page.getByRole('button',{name:'Novo instrumento',exact:true}).click();let dialog=page.getByRole('dialog');
 await dialog.getByLabel('Código interno RHDD',{exact:true}).fill('QA-MET-007');await dialog.getByLabel('Descrição',{exact:true}).fill('Instrumento QA de demonstração');await dialog.getByLabel('Obra',{exact:true}).fill('Obra QA');await dialog.getByLabel('Código de série / identificação',{exact:true}).fill('QA-SERIE-007');
 await dialog.getByRole('button',{name:'Continuar',exact:true}).click();await dialog.getByLabel('Tipo / família',{exact:true}).fill('Dimensional');await dialog.getByLabel('Modelo',{exact:true}).fill('QA-100');await dialog.getByLabel('Equipamento crítico',{exact:true}).fill('HI-LO (ESCALA)');await dialog.getByLabel('Faixa de medição',{exact:true}).fill('0 a 100 mm');await dialog.getByLabel('Faixa de utilização',{exact:true}).fill('0 a 80 mm');await dialog.getByLabel('Valor da divisão de verificação',{exact:true}).fill('0,1 mm');await dialog.getByRole('button',{name:'Adicionar grandeza / faixa'}).click();await dialog.getByLabel('Grandeza',{exact:true}).fill('Comprimento');await dialog.getByLabel('Unidade',{exact:true}).fill('mm');await dialog.getByLabel('Mínimo',{exact:true}).fill('0');await dialog.getByLabel('Máximo',{exact:true}).fill('100');
 await dialog.getByRole('button',{name:'Continuar',exact:true}).click();await dialog.getByLabel('Empresa proprietária',{exact:true}).selectOption({label:'CONSAG • demonstração'});await dialog.getByLabel('Equipamento de empresa contratada?',{exact:true}).selectOption('não');await dialog.getByLabel('Área/Setor responsável pela calibração',{exact:true}).fill('Qualidade QA');await dialog.getByLabel('Processo',{exact:true}).fill('Soldagem QA');await dialog.getByLabel('Local de uso',{exact:true}).fill('Oficina QA');
 await dialog.getByRole('button',{name:'Continuar',exact:true}).click();await dialog.getByLabel('Intervalo de calibrações (meses)',{exact:true}).fill('6');await dialog.getByLabel('Motivo',{exact:true}).fill('Intervalo confirmado pelo responsável no teste');await dialog.getByLabel('Evidência / referência',{exact:true}).fill('Evidência QA 001');
 await dialog.getByRole('button',{name:'Voltar',exact:true}).click();await expect(dialog.getByLabel('Empresa proprietária',{exact:true})).toHaveValue('10000000-0000-4000-8000-000000000001');await dialog.getByRole('button',{name:'Continuar',exact:true}).click();await expect(dialog.getByLabel('Intervalo de calibrações (meses)',{exact:true})).toHaveValue('6');await dialog.getByRole('button',{name:'Continuar',exact:true}).click();await dialog.getByRole('button',{name:'Salvar instrumento',exact:true}).click();await expect(page.getByRole('button',{name:'QA-MET-007',exact:true})).toBeVisible();checks.push('Cadastro em cinco etapas, múltiplas faixas, voltar preserva dados e periodicidade auditada');
 await page.getByLabel('Pesquisa global').fill('QA-SERIE-007');await expect(page.locator('.instrument-table tbody tr')).toHaveCount(1);await page.screenshot({path:'test-results/instruments-filtered-1440.png',fullPage:true});
 const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Exportar Excel',exact:true}).click();const download=await downloadPromise;await download.saveAs('test-results/Instrumentos_QA.xlsx');const book=XLSX.read(readFileSync('test-results/Instrumentos_QA.xlsx'),{type:'buffer'});const rows=XLSX.utils.sheet_to_json(book.Sheets[book.SheetNames[0]]);if(rows.length!==1||rows[0]['Código']!=='QA-MET-007')throw new Error('Exportação não respeitou filtro');checks.push('Busca por série e exportação Excel filtrada');
 await page.getByRole('button',{name:'QA-MET-007',exact:true}).click();dialog=page.getByRole('dialog');await dialog.getByRole('button',{name:'Registrar controle',exact:true}).click();dialog=page.getByRole('dialog');
 await dialog.getByLabel('Data da calibração',{exact:true}).fill('2026-10-02');await dialog.getByLabel('Próxima data',{exact:true}).fill('2027-04-02');await dialog.getByLabel('Entidade calibradora',{exact:true}).fill('Laboratório QA');await dialog.getByLabel('Laboratório acreditado?',{exact:true}).selectOption('não');await dialog.getByRole('button',{name:'Continuar',exact:true}).click();
 await dialog.getByLabel('Número do certificado',{exact:true}).fill('QA-CERT-001');await dialog.getByLabel('Anexo do certificado / registro',{exact:true}).setInputFiles({name:'certificado-qa.xlsx',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',buffer:Buffer.from([0x50,0x4b,0x03,0x04,0x14,0x00,0x00,0x00])});await expect(dialog.getByText('Anexo vinculado ao evento',{exact:true})).toBeVisible();await dialog.getByLabel('Código de série / identificação',{exact:true}).fill('QA-SERIE-007');await dialog.getByRole('button',{name:'Continuar',exact:true}).click();
 for(const [label,value]of [['Documento de referência da tolerância','PR-QA-001'],['Tolerância do processo','0,50'],['Incerteza de medição','0,10'],['Erro de medição','0,40']])await dialog.getByLabel(label,{exact:true}).fill(value);await dialog.getByLabel('% ou unidade',{exact:true}).selectOption('unidade');
 await dialog.getByRole('button',{name:'Continuar',exact:true}).click();const selects=dialog.locator('.checklist select');for(let i=0;i<await selects.count();i++)await selects.nth(i).selectOption('conforme');await dialog.getByRole('button',{name:'Continuar',exact:true}).click();await expect(dialog.getByText('não conforme',{exact:true}).first()).toBeVisible();await page.screenshot({path:'test-results/quantitative-equality.png',fullPage:true});await dialog.getByRole('button',{name:'Continuar',exact:true}).click();await dialog.getByLabel('Calibração aceita?',{exact:true}).selectOption('não');await dialog.getByLabel('Aceito com restrição?',{exact:true}).selectOption('não');await dialog.getByLabel('Status do cadastro',{exact:true}).selectOption('inativo');await dialog.getByLabel('Situação do equipamento',{exact:true}).selectOption('liberado para uso');await dialog.getByLabel('Justificativa / conclusão humana',{exact:true}).fill('Análise humana de demonstração');await dialog.getByRole('button',{name:'Registrar decisão',exact:true}).click();await expect(dialog.getByRole('alert')).toContainText('quantitativa');checks.push('Upload XLSX 16 MB, preenchimento atual, checklist e igualdade rejeitada na liberação');
 for(let i=0;i<3;i++)await dialog.getByRole('button',{name:'Voltar',exact:true}).click();await dialog.getByLabel('Erro de medição',{exact:true}).fill('0,39');for(let i=0;i<3;i++)await dialog.getByRole('button',{name:'Continuar',exact:true}).click();await dialog.getByRole('button',{name:'Registrar decisão',exact:true}).click();dialog=page.getByRole('dialog');await expect(dialog.getByText('concluído',{exact:true})).toBeVisible();await expect(dialog.getByText('liberado para uso',{exact:true}).first()).toBeVisible();await expect(dialog.getByText('inativo',{exact:true}).first()).toBeVisible();await expect(dialog.getByText('02/04/2027',{exact:true})).toBeVisible();await page.screenshot({path:'test-results/instrument-cycle.png',fullPage:true});await dialog.getByRole('button',{name:'Fechar',exact:true}).click();checks.push('Ciclo completo com aceitação/status/situação independentes e próxima data');
 await clickNav('Cadastros auxiliares');await page.getByRole('button',{name:'Novo item',exact:true}).click();dialog=page.getByRole('dialog');await dialog.getByLabel('Empresa proprietária',{exact:true}).selectOption({label:'CONSAG • demonstração'});await dialog.getByLabel('Nome',{exact:true}).fill('Dimensional QA');await dialog.getByRole('button',{name:'Salvar item',exact:true}).click();await expect(page.getByText('Dimensional QA',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Editar item',exact:true}).click();dialog=page.getByRole('dialog');await dialog.getByLabel('Situação',{exact:true}).selectOption('inativo');await dialog.getByRole('button',{name:'Salvar item',exact:true}).click();await expect(page.locator('#main tbody')).toContainText('inativo');checks.push('Cadastro auxiliar por empresa e inativação sem exclusão');
 await clickNav('Instrumentos');await page.getByRole('button',{name:'QA-MET-007',exact:true}).click();dialog=page.getByRole('dialog');await dialog.getByLabel('Anexar foto ou documento').setInputFiles({name:'manual-qa.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4\n%%EOF')});await expect(dialog.getByText('manual-qa.pdf',{exact:true})).toBeVisible();await dialog.getByRole('button',{name:'Fechar',exact:true}).click();await page.getByRole('button',{name:'QA-MET-007',exact:true}).click();dialog=page.getByRole('dialog');await expect(dialog.getByText('manual-qa.pdf',{exact:true})).toBeVisible();await dialog.getByRole('button',{name:'Fechar',exact:true}).click();checks.push('Anexo cadastral validado e preservado ao reabrir a ficha');
 await clickNav('Importar LI');await page.getByLabel('Planilha LI',{exact:true}).setInputFiles({name:'LI-QA.csv',mimeType:'text/csv',buffer:Buffer.from('Código;Descrição;Número de série\r\n0009;Paquímetro importado;001234\r\nQA-MET-007;Duplicado preservado;X\r\n;Descrição sem código;Y')});await page.getByRole('button',{name:'Ler planilha',exact:true}).click();await expect(page.getByRole('heading',{name:'Correspondência das colunas'})).toBeVisible();await page.getByLabel('Empresa proprietária da importação').selectOption({label:'CONSAG • demonstração'});await page.getByRole('button',{name:'Gerar prévia',exact:true}).click();await expect(page.getByText('1 duplicados',{exact:true})).toBeVisible();await expect(page.getByText('1 inválidos',{exact:true})).toBeVisible();const commit=page.getByRole('button',{name:'Confirmar importação de 1 instrumentos'});await expect(commit).toBeDisabled();await page.getByLabel(/Revisei o mapeamento/).check();await commit.click();await expect(page.getByText('Importação concluída: 1 criados, 0 duplicados preservados.',{exact:true})).toBeVisible();await page.screenshot({path:'test-results/li-import-result.png',fullPage:true});await page.getByLabel('Limpar pesquisa').click();await clickNav('Instrumentos');await page.getByLabel('Pesquisa global').fill('001234');await expect(page.locator('.instrument-table tbody tr')).toHaveCount(1);await page.getByRole('button',{name:'0009',exact:true}).click();dialog=page.getByRole('dialog');await expect(dialog.getByText('fora de uso',{exact:true})).toBeVisible();await expect(dialog.getByText('001234',{exact:true})).toBeVisible();await dialog.getByRole('button',{name:'Fechar',exact:true}).click();checks.push('LI em Worker: CSV UTF-8, zeros, mapeamento, duplicados, prévia e confirmação humana');
 await clickNav('Histórico de auditoria');await expect(page.locator('#main')).toContainText('Decisão metrológica');await expect(page.locator('#main')).toContainText('Cadastro de instrumento');
 await page.getByLabel('Limpar pesquisa').click();await clickNav('Visão geral');for(const width of [1366,1280]){await page.setViewportSize({width,height:900});await page.screenshot({path:`test-results/dashboard-${width}.png`,fullPage:true});const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);if(overflow)throw new Error(`Overflow desktop ${width}`);}checks.push('Layouts desktop 1440/1366/1280 sem overflow da página');
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'test-results/dashboard-390.png',fullPage:true});if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)){console.log(await page.evaluate(()=>[...document.querySelectorAll('body *')].filter(e=>e.getBoundingClientRect().right>innerWidth+1).map(e=>({tag:e.tagName,class:e.className,width:e.getBoundingClientRect().width,right:e.getBoundingClientRect().right})).slice(0,30)));throw new Error('Overflow mobile');}await page.getByRole('button',{name:'Abrir menu'}).click();await clickNav('Configurações e fases');await expect(page.locator('#main h1')).toHaveText('Configurações e fases');checks.push('Consulta mobile 390px e navegação acessível');
 await page.getByRole('button',{name:'Sair',exact:true}).click();await page.getByRole('button',{name:/Explorar demonstração/}).click();await page.getByLabel('Pesquisa global').fill('QA-MET-007');await expect(page.locator('.instrument-table tbody tr')).toHaveCount(0);checks.push('Sessão demonstrativa reinicia sem persistir dados reais');
 if(errors.length)throw new Error(errors.join('\n'));writeFileSync('test-results/browser-report.json',JSON.stringify({passed:true,checks,pageErrors:errors},null,2));console.log(JSON.stringify({passed:true,checks,pageErrors:errors},null,2));
}catch(error){writeFileSync('test-results/browser-report.json',JSON.stringify({passed:false,checks,pageErrors:errors,error:String(error)},null,2));throw error;}finally{await browser?.close();server.kill();}
