import {test} from 'node:test';
import assert from 'node:assert/strict';
import * as XLSX from 'xlsx';
import {readSheet} from '../src/workers/li-reader';
import {buildPreview,mappingErrors,suggestMapping} from '../src/domain/li-import';
import {inspectAsset} from '../src/domain/catalogs';
const company='10000000-0000-4000-8000-000000000001';
function workbook(rows:unknown[][],format:'xlsx'|'xls'='xlsx'){const book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,XLSX.utils.aoa_to_sheet(rows),'LI');XLSX.utils.book_append_sheet(book,XLSX.utils.aoa_to_sheet([['Código','Descrição'],['SECOND','Outro']]),'Segunda');const bytes=XLSX.write(book,{type:'array',bookType:format==='xls'?'biff8':'xlsx'});return bytes as ArrayBuffer;}
test('LI: CSV preserva zeros à esquerda e acentos',()=>{const data=readSheet(new TextEncoder().encode('Código;Descrição;Número de série\r\n0007;Paquímetro;00123').buffer);assert.equal(data.rows[0].values[0],'0007');assert.equal(data.rows[0].values[2],'00123');assert.equal(suggestMapping(data.headers).serial,2);});
test('LI: XLSX e XLS mantêm linhas físicas e permitem seleção da aba',()=>{for(const format of ['xlsx','xls']as const){const buffer=workbook([['Título da LI'],['Código','Descrição'],[],['0001','Micrômetro']],format);const data=readSheet(buffer,undefined,2);assert.equal(data.rows[0].rowNumber,4);assert.equal(data.rows[0].values[0],'0001');assert.deepEqual(data.sheets,['LI','Segunda']);assert.equal(readSheet(buffer,'Segunda').rows[0].values[0],'SECOND');}});
test('LI: mapeamento exige identificação independente e colunas únicas',()=>{assert.equal(suggestMapping(['TAG','Patrimônio','LI','Descrição']).code,undefined);assert.equal(mappingErrors({description:3}).length,1);assert.ok(mappingErrors({code:1,description:1}).some(e=>e.includes('diferente')));});
test('LI: prévia protege duplicados e rejeita periodicidade/fracionamento da faixa',()=>{const data=readSheet(workbook([['Código','Descrição','Periodicidade (meses)','Grandeza','Unidade','Mínimo','Máximo'],['A','Já existe','','','','',''],['b','Repetido','','','','',''],[' B ','Também repetido','','','','',''],['C','Inválido','0.5','Comprimento','mm','10','1'],['0008','Válido','6','Comprimento','mm','0','100']]));const preview=buildPreview(data.rows,suggestMapping(data.headers),company,[' a ']);assert.deepEqual(preview.map(r=>r.status),['duplicate','duplicate','duplicate','invalid','ready']);const i=preview.at(-1)!.instrument;assert.equal(i.code,'0008');assert.equal(i.operationalStatus,'fora de uso');assert.equal(i.nextControl,'');assert.equal(i.lastControl,'');assert.equal(i.periodicityMonths,6);assert.equal(i.capabilities[0].min,'0');});
test('LI: arquivo vazio, linha de cabeçalho e limite de 10.000 linhas',()=>{assert.throws(()=>readSheet(new TextEncoder().encode('Código;Descrição\n').buffer),/Não há dados/);assert.throws(()=>readSheet(workbook([['Código','Descrição'],['A','B']]),undefined,0),/cabeçalho/);assert.throws(()=>readSheet(workbook([['Código','Descrição'],...Array.from({length:10001},(_,i)=>[String(i),'Item'])])),/10.000/);});
test('Anexos: verifica assinatura, extensão e limite antes de enviar',async()=>{assert.deepEqual(await inspectAsset(new File(['%PDF-1.4\n%%EOF'],'manual.pdf')),{mimeType:'application/pdf',extension:'pdf'});assert.equal((await inspectAsset(new File([Uint8Array.from([137,80,78,71,13,10,26,10])],'foto.png'))).mimeType,'image/png');await assert.rejects(()=>inspectAsset(new File(['%PDF-1.4'],'foto.jpg')),/extensão/);await assert.rejects(()=>inspectAsset(new File(['texto falso'],'manual.pdf')),/conteúdo/);await assert.rejects(()=>inspectAsset(new File([new Uint8Array(10485761)],'manual.pdf')),/10 MB/);});
