import { test } from 'node:test';
import assert from 'node:assert/strict';
import {combinedQuantitativeOutcome,currentProcedureInstrumentErrors,evaluateCurrentProcedure,evaluatePoint,newChecklist,evaluateQualitative,emptyEvent,decisionErrors,identityDifferences,daysUntil,prepareEventForPersistence,visibleResultPoints} from '../src/domain/metrology';
import { demoState } from '../src/services/demo';
const point=(error:string,uncertainty:string,tolerance='0,50',unit='mm',toleranceUnit='mm')=>({error,uncertainty,tolerance,unit,toleranceUnit});
test('regra estrita: 0,49 conforme, igualdade e 0,51 não conformes',()=>{assert.equal(evaluatePoint(point('0,39','0,10')).status,'conforme');assert.equal(evaluatePoint(point('0,40','0,10')).status,'não conforme');assert.equal(evaluatePoint(point('0,41','0,10')).status,'não conforme');});
test('valores negativos são absolutos; zero é válido, tolerância zero não',()=>{assert.equal(evaluatePoint(point('-0,4','-0,1')).status,'não conforme');assert.equal(evaluatePoint(point('0','0')).status,'conforme');assert.equal(evaluatePoint(point('0','0','0')).status,'pendente');});
test('decimais exatos não sofrem arredondamento de ponto flutuante',()=>{assert.equal(evaluatePoint(point('0.1','0.2','0.3')).status,'não conforme');assert.equal(evaluatePoint(point('0.1','0.2','0.30000000000000000001')).status,'conforme');assert.equal(evaluatePoint(point('0.'+'1'.repeat(80),'0.'+'2'.repeat(80),'0.'+'3'.repeat(80))).status,'não conforme');});
test('campos ausentes, inválidos e unidades incompatíveis são pendentes',()=>{for(const p of [point('','0.1'),point('Infinity','0'),point('NaN','0'),point('1.000,1','0'),point('0','0','','mm','mm'),point('0','0','1','mm','cm'),point('0','0','1','',''),point('0','0','-1')])assert.equal(evaluatePoint(p).status,'pendente');});
test('checklist completo, justificativas N/A, não conformidade e itens adulterados',()=>{const c=newChecklist();assert.equal(evaluateQualitative(c),'pendente');c.forEach(x=>x.outcome='conforme');assert.equal(evaluateQualitative(c),'conforme');c[0].outcome='não aplicável';assert.equal(evaluateQualitative(c),'pendente');c[0].notes='Não se aplica à verificação';assert.equal(evaluateQualitative(c),'conforme');c[0].outcome='não conforme';assert.equal(evaluateQualitative(c),'não conforme');assert.equal(evaluateQualitative(c.slice(1)),'pendente');});
function completedEvent(){
 const e=emptyEvent('test','ativo');e.date='2026-10-02';e.nextDate='2027-04-02';e.certificateNumber='123';e.laboratory='Laboratório externo';e.laboratoryAccredited='não';e.attachmentPath='path.xlsx';e.toleranceReferenceDocument='Procedimento QA';e.processTolerance='0,50';e.measurementUncertainty='0,10';e.measurementError='0,39';e.resultBasis='unidade';e.calibrationAccepted='não';e.acceptedWithRestriction='não';e.rationale='Análise humana';e.decision='liberado para uso';e.checklist.forEach(x=>x.outcome='conforme');return e;
}
test('preenchimento atual usa a mesma regra quantitativa e não exige ponto detalhado',()=>{const e=completedEvent();assert.equal(evaluateCurrentProcedure(e).status,'conforme');assert.equal(combinedQuantitativeOutcome(e),'conforme');assert.deepEqual(decisionErrors(e),[]);e.measurementError='0,40';assert.equal(evaluateCurrentProcedure(e).status,'não conforme');assert.ok(decisionErrors(e).some(x=>x.includes('quantitativa')));e.measurementError='0';e.measurementUncertainty='0';e.processTolerance='0';assert.equal(evaluateCurrentProcedure(e).status,'pendente');});
test('laboratório acreditado, aceitação, status e situação permanecem independentes',()=>{const e=completedEvent();e.laboratoryAccredited='não';e.calibrationAccepted='não';e.registrationStatus='inativo';e.decision='liberado para uso';assert.deepEqual(decisionErrors(e),[]);});
test('ponto canônico do procedimento é persistido sem aparecer como ponto detalhado',()=>{const e=completedEvent();const saved=prepareEventForPersistence(e);assert.equal(saved.points.length,1);assert.equal(visibleResultPoints(saved.points).length,0);assert.equal(saved.points[0].error,'0,39');const again=prepareEventForPersistence(saved);assert.equal(again.points.length,1);assert.equal(again.points[0].id,saved.points[0].id);});
test('campos atuais do cadastro são obrigatórios apenas para concluir o ciclo',()=>{const i=demoState().instruments[0];i.periodicityMonths=12;assert.deepEqual(currentProcedureInstrumentErrors(i),[]);i.workSite='';assert.ok(currentProcedureInstrumentErrors(i).some(x=>x.includes('Obra')));});
test('identificações de certificado divergentes ficam visíveis',()=>{const i=demoState().instruments[0],e=emptyEvent(i.id);e.certificateIdentity.serial='OUTRA SERIE';const d=identityDifferences(i,e);assert.equal(d.length,1);assert.equal(d[0].registered,i.serial);assert.equal(d[0].certificate,'OUTRA SERIE');});
test('vencimentos consideram dias de calendário e campos pendentes',()=>{assert.equal(daysUntil('2026-10-02','2026-10-02'),0);assert.equal(daysUntil('2026-10-01','2026-10-02'),-1);assert.equal(daysUntil('','2026-10-02'),null);});
