import {test} from 'node:test';import assert from 'node:assert/strict';import {PGlite} from '@electric-sql/pglite';import {readFileSync,readdirSync} from 'node:fs';
import {demoState} from '../src/services/demo';import {emptyInstrument} from '../src/domain/metrology';import {newCertificate} from '../src/domain/minimal';
test('PostgreSQL mínimo: cadastro → responsável → monitoramento → renovação, RBAC/RLS e histórico',async t=>{const db=new PGlite();try{
 await db.exec(`create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz);create function auth.uid()returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to anon,authenticated;grant execute on function auth.uid()to anon,authenticated;create schema storage;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text,owner_id text,metadata jsonb);alter table storage.objects enable row level security;grant usage on schema storage to authenticated;grant select,insert on storage.objects to authenticated;`);
 const directory=new URL('../supabase/migrations/',import.meta.url);for(const name of readdirSync(directory).filter(n=>n.endsWith('.sql')).sort())await db.exec(readFileSync(new URL(name,directory),'utf8'));
 const owner=crypto.randomUUID(),analyst=crypto.randomUUID(),responsible=crypto.randomUUID(),viewer=crypto.randomUUID(),outsider=crypto.randomUUID();const companies=demoState().companies;const company=companies[0],other=companies[1];
 await db.query('insert into auth.users(id,email,email_confirmed_at)values($1,$2,now()),($3,$4,now()),($5,$6,now()),($7,$8,now()),($9,$10,now())',[owner,'owner@example.test',analyst,'cadastro@example.test',responsible,'responsavel@example.test',viewer,'consulta@example.test',outsider,'semperfil@example.test']);
 for(const c of companies)await db.query('insert into public.companies(id,name,data)values($1,$2,$3)',[c.id,c.name,c]);
 await db.query("insert into private.members(user_id,role,company_id)values($1,'owner',null),($2,'analyst',$5),($3,'quality_admin',$5),($4,'viewer',$6)",[owner,analyst,responsible,viewer,company.id,other.id]);
 await db.query("insert into public.li_references(prefix,document,source_name,source_hash,original_max,planned_max,next_number,next_row,created_by)values('CE-','LI teste','LI teste','hash',1,842,843,850,$1)",[owner]);
 const auth=async(id:string,role='authenticated')=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec(`set role ${role}`);};const rpc=async(name:string,args:unknown[]=[])=>((await db.query<{result:any}>(`select public.${name}(${args.map((_,n)=>'$'+(n+1)).join(',')}) as result`,args)).rows[0].result);
 let instrument={...emptyInstrument(),...demoState().instruments[0],id:crypto.randomUUID(),liNumber:'',code:'',liSource:undefined};const id=crypto.randomUUID();let c={...newCertificate(instrument.id),date:'2026-01-01',nextDate:'2026-12-31',laboratory:'Laboratório',certificateNumber:'CERT-1',toleranceReferenceDocument:'Referência',measurementError:'0.4',measurementUncertainty:'0.1',processTolerance:'0.5',resultBasis:'unidade' as const,laboratoryAccredited:'não' as const,calibrationAccepted:'sim' as const,acceptedWithRestriction:'não' as const,decision:'liberado para uso' as const};let record:any={id,instrument,certificate:c};
 await auth(analyst);
 await t.test('cadastro recebe LI; tentativas pelas APIs anteriores não contornam aprovação',async()=>{record=await rpc('save_simple_registration',[record,false]);assert.equal(record.instrument.liNumber,'CE-843');assert.equal(record.quantitative.status,'conforme');assert.equal(record.state,'rascunho');for(const name of ['save_instrument','save_metrological_event','save_calibration_laboratory','prepare_li_certificate'])await assert.rejects(()=>rpc(name,name==='save_instrument'?[instrument,'','']:name==='save_metrological_event'?[{},true]:[{}]),/permission denied/);assert.equal((await db.query<{data:any}>('select data from public.instruments where id=$1',[instrument.id])).rows[0].data.nextControl,'');await assert.rejects(()=>rpc('review_simple_registration',[id,true,'']),/responsável/);});
 await t.test('envio valida anexo real, dados e escopo; snapshot ignorado/resultado recalculado',async()=>{await assert.rejects(()=>rpc('save_simple_registration',[{...record,certificate:{...c,attachmentPath:`${instrument.id}/${id}/${crypto.randomUUID()}.pdf`}},true]),/Anexo inexistente/);c.attachmentPath=`${instrument.id}/${id}/${crypto.randomUUID()}.pdf`;c.attachmentName='cert1.pdf';await db.query('insert into storage.objects(bucket_id,name,owner_id,metadata)values($1,$2,$3,$4)',['metrology-certificates',c.attachmentPath,analyst,{mimetype:'application/pdf',size:100}]);await assert.rejects(()=>rpc('save_simple_registration',[{...record,instrument:{...record.instrument,ownerCompanyId:other.id},certificate:c},true]),/Empresa/);record=await rpc('save_simple_registration',[{...record,certificate:c,quantitative:{status:'FORJADO'}},true]);assert.equal(record.state,'aguardando aprovação');assert.equal(record.quantitative.status,'conforme');await assert.rejects(()=>rpc('save_simple_registration',[record,false]),/imutável/);});
 await auth(responsible);
 await t.test('responsável devolve com motivo; cadastro corrige e reenvia',async()=>{await assert.rejects(()=>rpc('review_simple_registration',[id,false,'']),/motivo/);record=await rpc('review_simple_registration',[id,false,'Conferir referência']);assert.equal(record.state,'devolvido');await auth(analyst);record=await rpc('save_simple_registration',[record,true]);assert.equal(record.state,'aguardando aprovação');await auth(responsible);record=await rpc('review_simple_registration',[id,true,'Conferido']);assert.equal(record.state,'aprovado');assert.equal(record.reviewedBy,responsible);await assert.rejects(()=>rpc('review_simple_registration',[id,true,'']),/não está/);const master=(await db.query<{data:any}>('select data from public.instruments where id=$1',[instrument.id])).rows[0].data;assert.equal(master.nextControl,'2026-12-31');assert.equal(master.currentCertificate.certificateNumber,'CERT-1');});
 await t.test('renovar aguarda aprovação, conserva certificado anterior e mesma LI',async()=>{await auth(analyst);const current=(await db.query<{data:any}>('select data from public.instruments where id=$1',[instrument.id])).rows[0].data;const rid=crypto.randomUUID(),path=`${instrument.id}/${rid}/${crypto.randomUUID()}.pdf`;await db.query('insert into storage.objects(bucket_id,name,owner_id,metadata)values($1,$2,$3,$4)',['metrology-certificates',path,analyst,{mimetype:'application/pdf',size:100}]);const renewal={id:rid,instrument:{...current,liNumber:'CE-FORJADO'},certificate:{...c,certificateNumber:'CERT-2',date:'2026-12-01',nextDate:'2027-12-01',attachmentPath:path}};const submitted=await rpc('save_simple_registration',[renewal,true]);assert.equal(submitted.version,2);assert.equal(submitted.instrument.liNumber,'CE-843');assert.equal((await db.query<{data:any}>('select data from public.instruments where id=$1',[instrument.id])).rows[0].data.currentCertificate.certificateNumber,'CERT-1');await auth(responsible);await rpc('review_simple_registration',[rid,true,'Renovação conferida']);const versions=(await db.query<{certificate_data:any}>('select certificate_data from public.instrument_registrations where instrument_id=$1 order by version',[instrument.id])).rows;assert.equal(versions.length,2);assert.equal(versions[0].certificate_data.certificateNumber,'CERT-1');assert.equal(versions[0].certificate_data.attachmentPath,c.attachmentPath);assert.equal(versions[1].certificate_data.certificateNumber,'CERT-2');assert.equal((await db.query<{next_number:number}>('select next_number from public.li_references')).rows[0].next_number,844);});
 await t.test('monitoramento consulta toda a base, filtros e perfis não expõem outra empresa',async()=>{const list=await rpc('minimal_workspace',['','todos',30,0]);assert.equal(list.total,1);assert.equal(list.items[0].instrument.currentCertificate.certificateNumber,'CERT-2');assert.equal((await rpc('minimal_workspace',['SEMRESULTADO','todos',30,0])).total,0);await auth(viewer);assert.equal((await rpc('minimal_workspace',['','todos',30,0])).total,0);assert.equal((await db.query('select * from public.instrument_registrations')).rows.length,0);assert.equal((await db.query('select * from storage.objects')).rows.length,0);await assert.rejects(()=>rpc('save_simple_registration',[record,false]),/Permissão/);await assert.rejects(()=>rpc('minimal_members'),/proprietário/);});
 await auth(owner);await t.test('somente proprietário concede perfis; revogação é imediata e owner protegido',async()=>{await assert.rejects(()=>rpc('set_minimal_member',['owner@example.test','analyst',null,false]),/Proprietário/);await assert.rejects(()=>rpc('set_minimal_member',['semperfil@example.test','owner',null,true]),/Perfil inválido/);await rpc('set_minimal_member',['semperfil@example.test','viewer',company.id,true]);await auth(outsider);assert.equal((await rpc('minimal_workspace',['','todos',30,0])).total,1);await auth(owner);await rpc('set_minimal_member',['semperfil@example.test','viewer',company.id,false]);await auth(outsider);await assert.rejects(()=>rpc('minimal_workspace',['','todos',30,0]),/Sem permissão/);await auth(analyst);await assert.rejects(()=>rpc('set_minimal_member',['consulta@example.test','quality_admin',null,true]),/proprietário/);await assert.rejects(()=>db.query('delete from public.instrument_registrations'),/permission denied/);await auth('','anon');await assert.rejects(()=>rpc('minimal_context'),/permission denied/);});

 await t.test('monitoramento pagina depois de filtrar e contabiliza toda a base autorizada',async()=>{await db.exec('reset role');const today=new Date().toLocaleDateString('en-CA',{timeZone:'America/Recife'});for(let n=0;n<55;n++){const i={...emptyInstrument(),id:crypto.randomUUID(),ownerCompanyId:company.id,code:'PAG-'+String(n).padStart(3,'0'),liNumber:'PAG-'+String(n).padStart(3,'0'),criticality:'Paginação',serial:'PAG-'+n,lastControl:'2026-01-01',nextControl:today};await db.query('insert into public.instruments(id,code,company_id,registration_status,operational_status,next_control,data)values($1,$2,$3,$4,$5,$6,$7)',[i.id,i.code,company.id,'ativo','fora de uso',today,i]);}await auth(owner);const first=await rpc('minimal_workspace',['PAG-','proximos',30,0]),second=await rpc('minimal_workspace',['PAG-','proximos',30,1]);assert.equal(first.total,55);assert.equal(first.items.length,50);assert.equal(second.items.length,5);assert.equal(first.metrics.total,56);assert.equal(new Set([...first.items,...second.items].map((r:any)=>r.instrument.id)).size,55);});
 }finally{await db.close();}});
