import {test} from 'node:test';
import assert from 'node:assert/strict';
import {newCertificate,evaluateSimple,monitoringStatus,suggestExpiry,simpleErrors,sccSituations} from '../src/domain/minimal';
import {demoState} from '../src/services/demo';
import {emptyInstrument} from '../src/domain/metrology';
test('cadastro mínimo: igualdade é conforme pela nova orientação; decimais e negativos são exatos',()=>{const c={...newCertificate('id'),measurementError:'-0,4',measurementUncertainty:'-0,1',processTolerance:'0,5',resultBasis:'unidade' as const};assert.equal(evaluateSimple(c).status,'conforme');assert.equal(evaluateSimple(c).total,'0.5');assert.equal(evaluateSimple({...c,measurementError:'0.40000000000000000000000000001'}).status,'não conforme');assert.equal(evaluateSimple({...c,processTolerance:'0'}).status,'pendente');assert.equal(evaluateSimple({...c,measurementError:''}).status,'pendente');});
test('monitoramento usa calendário e janela explícita; sugestão de meses não muda a data original',()=>{const i={...emptyInstrument(),lastControl:'2026-01-01',nextControl:'2026-10-06'};assert.equal(monitoringStatus(i,30,'2026-10-06'),'próximo do vencimento');assert.equal(monitoringStatus(i,30,'2026-10-07'),'vencido');assert.equal(monitoringStatus({...i,nextControl:'2026-11-06'},30,'2026-10-06'),'em dia');assert.equal(suggestExpiry('2026-01-31',1),'2026-02-28');assert.equal(suggestExpiry('2024-01-31',1),'2024-02-29');assert.equal(suggestExpiry('',1),'');});

test('instruções SCC: campos condicionais e sete situações preservam respostas independentes',()=>{const i={...demoState().instruments[0],contractorEquipment:'não' as const};const c={...newCertificate(i.id),date:'2026-10-06',nextDate:'2027-10-06',laboratory:'QA',certificateNumber:'QA-1',toleranceReferenceDocument:'Referência',measurementError:'0.4',measurementUncertainty:'0.1',processTolerance:'0.5',resultBasis:'unidade' as const,laboratoryAccredited:'sim' as const,calibrationAccepted:'não' as const,acceptedWithRestriction:'não' as const,decision:'enviado para calibração' as const,attachmentPath:'QA'};assert.deepEqual(simpleErrors(i,c),[]);assert.ok(simpleErrors(i,{...c,laboratoryAccredited:'não'}).some(e=>e.includes('rastreabilidade')));assert.deepEqual(simpleErrors(i,{...c,laboratoryAccredited:'não',standardsValidation:'não'}),[]);assert.ok(simpleErrors(i,{...c,acceptedWithRestriction:'sim'}).some(e=>e.includes('Restrição')));assert.ok(simpleErrors({...i,contractorEquipment:'sim'},c).some(e=>e.includes('Empresa contratada')));assert.deepEqual(simpleErrors({...i,contractorEquipment:'sim',contractorCompanyName:'Contratada QA'},{...c,acceptedWithRestriction:'sim',restrictionText:'Faixa limitada'}),[]);assert.equal(sccSituations.length,7);for(const decision of sccSituations)assert.deepEqual(simpleErrors(i,{...c,decision}),[]);assert.ok(simpleErrors(i,{...c,decision:'liberado para uso'}).some(e=>e.includes('SCC')));assert.equal(c.calibrationAccepted,'não');});
