import {useMemo,useState} from 'react';
import type {TraceabilityData,TraceabilitySelection,TraceabilitySnapshot} from '../domain/traceability';
import {historicalValidity,laboratoryValidity} from '../domain/traceability';
import {Badge,Field} from './Primitives';

export function EventTraceabilityPicker({data,companyId,date,laboratoryId,selections,onChange,loading,error}:{data:TraceabilityData;companyId:string;date:string;laboratoryId:string;selections:TraceabilitySelection[];onChange:(labId:string,selections:TraceabilitySelection[])=>void;loading:boolean;error:string}){
 const [query,setQuery]=useState('');
 const standardById=useMemo(()=>new Map(data.standards.map(s=>[s.id,s])),[data.standards]);
 const selectedById=new Map(selections.map(s=>[s.certificateId,s]));
 const lab=data.laboratories.find(l=>l.id===laboratoryId);
 const options=data.certificates.filter(c=>c.companyId===companyId).filter(c=>{
  const standard=standardById.get(c.standardId);return standard&&(standard.active||selectedById.has(c.id))&&[standard.name,standard.serial,c.number].join(' ').toLocaleLowerCase('pt-BR').includes(query.toLocaleLowerCase('pt-BR'));
 }).sort((a,b)=>a.standardId.localeCompare(b.standardId)||b.version-a.version);
 return <details className="trace-picker"><summary>Vincular laboratório e padrões desta calibração</summary><p className="muted">Vínculos complementares. A validade é conferida na data da calibração; escopo e rastreabilidade precisam de análise humana.</p>{loading&&<p role="status">Carregando referências…</p>}{error&&<p className="error" role="alert">{error}</p>}<Field label="Laboratório cadastrado para este evento"><select disabled={loading||!!error} value={laboratoryId} onChange={e=>onChange(e.target.value,selections)}><option value="">Sem vínculo cadastral</option>{data.laboratories.filter(l=>l.companyId===companyId&&(l.active||l.id===laboratoryId)).map(l=><option key={l.id} value={l.id}>{l.name}{l.active?'':' (inativo)'}</option>)}</select></Field>{lab&&<p>Acreditação cadastral: <Badge>{laboratoryValidity(lab,date)}</Badge> · Escopo: {lab.scope||'não informado'}</p>}<Field label="Pesquisar certificados de padrões"><input value={query} onChange={e=>setQuery(e.target.value)} disabled={loading||!!error}/></Field><div className="trace-option-list">{options.slice(0,100).map(c=>{
  const standard=standardById.get(c.standardId)!;const selected=selectedById.get(c.id);
  return <div className="trace-option" key={c.id}><label><input type="checkbox" checked={!!selected} onChange={e=>onChange(laboratoryId,e.target.checked?[...selections,{certificateId:c.id,usage:''}]:selections.filter(s=>s.certificateId!==c.id))}/><span>{standard.name} · {standard.serial} · {c.number} · versão {c.version}</span></label><Badge>{historicalValidity(date,c.calibrationDate,c.validUntil)}</Badge><small>Calibrado: {c.calibrationDate} · Validade: {c.validUntil||'não informada'} · {c.attachmentPath?'arquivo anexado':'sem arquivo'}</small>{selected&&<Field label={`Uso do padrão ${c.number}`}><input maxLength={2000} value={selected.usage} onChange={e=>onChange(laboratoryId,selections.map(s=>s.certificateId===c.id?{...s,usage:e.target.value}:s))}/></Field>}</div>;
 })}</div>{options.length>100&&<p className="muted">Mostrando 100 opções. Refine a pesquisa para encontrar outro certificado.</p>}{!loading&&!error&&!options.length&&<p>Nenhum certificado de padrão encontrado para esta empresa.</p>}<p className="notice">Selecionar um laboratório ou padrão não altera “Laboratório acreditado?”, “Calibração aceita?” nem a situação do equipamento. Os registros são preservados ao concluir o evento.</p></details>;
}
export function EventTraceabilityView({snapshot,onOpen}:{snapshot?:TraceabilitySnapshot;onOpen:(path:string)=>Promise<void>}){
 const [error,setError]=useState('');
 if(!snapshot||(!snapshot.laboratory&&!snapshot.standards.length))return null;
 return <section className="trace-history"><h4>Rastreabilidade registrada na calibração</h4><p className="muted">Data do evento: {snapshot.eventDate||'pendente'}. Dados preservados com este ciclo.</p>{snapshot.laboratory&&<p>Laboratório: <strong>{snapshot.laboratory.record.name}</strong> · <Badge>{snapshot.laboratory.validity}</Badge><small className="block">Referência: {snapshot.laboratory.record.accreditationReference||'não informada'} · Escopo: {snapshot.laboratory.record.scope||'não informado'}</small></p>}{snapshot.standards.map(s=><article className="trace-card" key={s.certificate.id}><strong>{s.standard.name} · {s.standard.serial}</strong><p>{s.certificate.number} · versão {s.certificate.version} · <Badge>{s.validity}</Badge></p><p>Emissor: {s.certificate.issuer} · Calibrado: {s.certificate.calibrationDate} · Validade: {s.certificate.validUntil||'não informada'}</p><p>Escopo: {s.certificate.scope||'não informado'} · Uso: {s.usage||'não informado'}</p><p>Rastreabilidade: {s.certificate.traceabilityEvidence||'não informada'}</p>{s.certificate.attachmentPath&&<button className="secondary" onClick={async()=>{setError('');try{await onOpen(s.certificate.attachmentPath);}catch(e){setError((e as Error).message);}}}>Abrir padrão {s.certificate.number}</button>}</article>)}{error&&<p className="error" role="alert">{error}</p>}</section>;
}
