import { useState } from 'react';
import type { Instrument, MetrologicalEvent, Restriction, ResultPoint } from '../domain/types';
import { decisionErrors, evaluatePoint, evaluateQualitative, identityDifferences } from '../domain/metrology';
import { Badge, Field, Steps } from './Primitives';
export default function EventForm({initial,instrument,onSave,onUpload,onCancel,busy}:{initial:MetrologicalEvent;instrument:Instrument;onSave:(e:MetrologicalEvent,conclude:boolean)=>Promise<void>;onUpload:(e:MetrologicalEvent,f:File)=>Promise<string>;onCancel:()=>void;busy:boolean}) {
  const [draft,setDraft]=useState(initial),[step,setStep]=useState(0),[errors,setErrors]=useState<string[]>([]),[uploading,setUploading]=useState(false);
  const set=<K extends keyof MetrologicalEvent>(key:K,value:MetrologicalEvent[K])=>setDraft(d=>({...d,[key]:value}));
  const diffs=identityDifferences(instrument,draft);
  function newPoint():ResultPoint {return {id:crypto.randomUUID(),reference:'',indicated:'',error:'',uncertainty:'',tolerance:'',unit:'',toleranceUnit:'',quantity:'',k:'',veff:'',direction:'',notes:''};}
  const outcomes=draft.points.map(evaluatePoint);
  return <form className="wizard" onSubmit={async e=>{e.preventDefault();const found=decisionErrors(draft);if(diffs.length&&!draft.divergenceJustification.trim())found.push('Justifique a divergência entre certificado e cadastro.');setErrors(found);if(found.length)return;await onSave(draft,true);}}>
  <Steps labels={['Evento','Certificado','Resultados','Qualitativa','Quantitativa','Decisão']} step={step}/>
  <section className="wizard-body"><div className="section-title"><h3>{['Controle metrológico','Certificado e identificação','Grandezas e pontos','Análise qualitativa','Análise quantitativa','Decisão humana'][step]}</h3><Badge>{instrument.code}</Badge></div>
  {step===0&&<div className="form-grid"><Field label="Tipo de controle"><select value={draft.type} onChange={e=>set('type',e.target.value as MetrologicalEvent['type'])}><option>calibração externa</option><option>verificação interna</option></select></Field><Field label="Data da calibração / verificação"><input type="date" value={draft.date} onChange={e=>set('date',e.target.value)}/></Field><Field label="Laboratório / executor"><input value={draft.laboratory} onChange={e=>set('laboratory',e.target.value)}/></Field><Field label="Próxima data" hint="Confirmada pelo responsável; sem frequência automática."><input type="date" value={draft.nextDate} onChange={e=>set('nextDate',e.target.value)}/></Field></div>}
  {step===1&&<><div className="form-grid"><Field label="Número do certificado / registro"><input value={draft.certificateNumber} onChange={e=>set('certificateNumber',e.target.value)}/></Field><Field label="Certificado / registro em PDF" hint="Digital ou escaneado. Até 20 MB. Não há aprovação ou leitura automática."><input type="file" accept="application/pdf,.pdf" disabled={uploading} onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setUploading(true);try{set('attachmentPath',await onUpload(draft,file));setErrors([]);}catch(error){setErrors([(error as Error).message]);}finally{setUploading(false);}}}/>{draft.attachmentPath&&<small>PDF anexado ao evento</small>}</Field></div><h4>Identificação informada no certificado</h4><div className="form-grid">{(['serial','tag','manufacturer','model'] as const).map((key,i)=><Field key={key} label={['Número de série','TAG','Fabricante','Modelo'][i]}><input value={draft.certificateIdentity[key]} onChange={e=>set('certificateIdentity',{...draft.certificateIdentity,[key]:e.target.value})}/></Field>)}</div>{diffs.length>0&&<div className="notice warning"><h4>Divergência encontrada</h4><table><thead><tr><th>Campo</th><th>Cadastro</th><th>Certificado</th></tr></thead><tbody>{diffs.map(d=><tr key={d.field}><td>{d.field}</td><td>{d.registered||'—'}</td><td>{d.certificate}</td></tr>)}</tbody></table><Field label="Justificativa da divergência" hint="Pode corrigir a leitura acima ou cancelar para corrigir o cadastro. A aceitação requer autorização no banco."><textarea value={draft.divergenceJustification} onChange={e=>set('divergenceJustification',e.target.value)}/></Field></div>}</>}
  {step===2&&<><p className="muted">Use a tolerância do processo confirmada pelo responsável. Todas as unidades devem coincidir; conversões não são presumidas.</p>{draft.points.map((point,index)=><section className="point-card" key={point.id}><div className="section-title"><h4>Ponto {index+1} • {point.quantity||'Grandeza pendente'}</h4><button type="button" className="text-button" onClick={()=>set('points',draft.points.filter(p=>p.id!==point.id))}>Remover ponto</button></div><div className="form-grid three">{(['quantity','unit','reference','indicated','error','uncertainty','tolerance','toleranceUnit','k','veff','direction','notes'] as const).map((key,i)=><Field key={key} label={['Grandeza / grupo','Unidade do resultado','Valor de referência','Valor indicado','Erro / tendência','Incerteza','Tolerância do processo','Unidade da tolerância','Fator k','Veff','Direção / ciclo','Observações'][i]}><input value={point[key]} onChange={e=>set('points',draft.points.map((p,j)=>j===index?{...p,[key]:e.target.value}:p))}/></Field>)}</div></section>)}<button type="button" className="secondary" onClick={()=>set('points',[...draft.points,newPoint()])}>Adicionar ponto de calibração</button></>}
  {step===3&&<><div className="section-title"><p className="muted">Cada item deve ser revisado. “Não aplicável” exige justificativa.</p><Badge>{evaluateQualitative(draft.checklist)}</Badge></div><div className="checklist">{draft.checklist.map((item,index)=><div className="checklist-item" key={item.key}><label><strong>{index+1}. {item.label}</strong><select aria-label={item.label} value={item.outcome} onChange={e=>set('checklist',draft.checklist.map((x,j)=>j===index?{...x,outcome:e.target.value as typeof item.outcome}:x))}><option value="">Pendente</option><option>conforme</option><option>não conforme</option><option>não aplicável</option></select></label><div><input aria-label={`Observação: ${item.label}`} placeholder="Observação / justificativa" value={item.notes} onChange={e=>set('checklist',draft.checklist.map((x,j)=>j===index?{...x,notes:e.target.value}:x))}/><input aria-label={`Evidência: ${item.label}`} placeholder="Evidência / referência" value={item.evidence} onChange={e=>set('checklist',draft.checklist.map((x,j)=>j===index?{...x,evidence:e.target.value}:x))}/></div></div>)}</div></>}
  {step===4&&<><div className="rule-box"><span>PR CONSAG 220 42 • item 3.1.6</span><strong>|Erro| + |Incerteza| &lt; Tolerância do Processo</strong><small>Igualdade é não conforme. Campos ausentes ou unidades incompatíveis permanecem pendentes.</small></div><table><thead><tr><th>Ponto / grandeza</th><th>|Erro| + |Incerteza|</th><th>Tolerância</th><th>Margem</th><th>Resultado</th></tr></thead><tbody>{draft.points.map((p,i)=><tr key={p.id}><td>{i+1} • {p.quantity}</td><td>{outcomes[i].total||'—'} {p.unit}</td><td>{p.tolerance||'—'} {p.toleranceUnit}</td><td>{outcomes[i].margin||'—'}</td><td><Badge>{outcomes[i].status}</Badge><small className="block">{outcomes[i].reason}</small></td></tr>)}</tbody></table>{!draft.points.length&&<p className="notice">Adicione resultados para realizar a análise quantitativa.</p>}<p className="muted">A liberação será validada novamente pelo banco. A análise não libera o instrumento automaticamente.</p></>}
  {step===5&&<><div className="form-grid"><Field label="Situação operacional"><select value={draft.decision} onChange={e=>{const decision=e.target.value as MetrologicalEvent['decision'];set('decision',decision);if(decision==='uso condicionado'&&!draft.restriction)set('restriction',{type:'',description:'',authorizedRange:'',allowedProcesses:'',forbiddenProcesses:'',deadline:'',authorizer:'',evidence:'',notes:''});}}><option value="">Escolha a decisão</option>{['liberado para uso','uso condicionado','fora de uso','segregado'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Justificativa / conclusão humana"><textarea value={draft.rationale} onChange={e=>set('rationale',e.target.value)}/></Field></div>{draft.decision==='uso condicionado'&&draft.restriction&&<div className="notice warning"><h4>Restrição de uso estruturada</h4><p>Quem autoriza e os critérios de uso condicionado: configuração RHDD pendente. Na produção, a permissão específica precisa ser concedida pelo owner.</p><div className="form-grid">{(Object.keys(draft.restriction) as Array<keyof Restriction>).map((key,i)=><Field key={key} label={['Tipo de restrição','Descrição','Faixa autorizada','Processos permitidos','Processos não permitidos','Data limite','Responsável pela autorização','Documento/evidência','Observações'][i]}><input type={key==='deadline'?'date':'text'} value={draft.restriction![key]} onChange={e=>set('restriction',{...draft.restriction!,[key]:e.target.value})}/></Field>)}</div></div>}{(draft.decision==='segregado'||draft.decision==='fora de uso')&&<div className="notice">Em caso de reprovação, o procedimento requer segregação, RNC e avaliação de impacto. O fluxo da PR CONSAG 220 43 está pendente e não foi inventado. Esta entrega preserva a decisão e o histórico; a RNC será implementada na fase 11.</div>}<dl className="review-summary"><div><dt>Qualitativa</dt><dd><Badge>{evaluateQualitative(draft.checklist)}</Badge></dd></div><div><dt>Quantitativa</dt><dd><Badge>{!outcomes.length||outcomes.some(x=>x.status==='pendente')?'pendente':outcomes.some(x=>x.status==='não conforme')?'não conforme':'conforme'}</Badge></dd></div></dl></>}
  {errors.length>0&&<div className="notice danger" role="alert"><strong>Revise antes de continuar</strong><ul>{errors.map((e,i)=><li key={i}>{e}</li>)}</ul></div>}
  </section><footer className="wizard-footer"><button type="button" className="secondary" disabled={busy||uploading} onClick={()=>onSave(draft,false)}>Salvar rascunho</button><div><button type="button" className="text-button" onClick={onCancel} disabled={busy}>Cancelar</button>{step>0&&<button type="button" className="secondary" onClick={()=>setStep(s=>s-1)}>Voltar</button>}{step<5?<button key="continue" type="button" className="primary" onClick={e=>{e.preventDefault();setStep(s=>s+1);}} disabled={uploading}>Continuar</button>:<button key="conclude" type="submit" className="primary" disabled={busy||uploading}>{busy?'Registrando…':'Registrar decisão'}</button>}</div></footer></form>;
}
