import { useState } from 'react';
import type { Company, Instrument } from '../domain/types';
import { Field, Steps } from './Primitives';
import type {CatalogEntry,CatalogKind} from '../domain/catalogs';
import { decimal } from '../domain/metrology';
export default function InstrumentForm({initial,companies,catalogs,onSave,onCancel,busy}:{initial:Instrument;companies:Company[];catalogs:CatalogEntry[];onSave:(i:Instrument,reason:string,evidence:string)=>Promise<void>;onCancel:()=>void;busy:boolean}) {
  const [draft,setDraft]=useState(initial),[step,setStep]=useState(0),[errors,setErrors]=useState<Record<string,string>>({}),[reason,setReason]=useState(''),[evidence,setEvidence]=useState('');
  function set<K extends keyof Instrument>(k:K,v:Instrument[K]) {setDraft(d=>({...d,[k]:v}));setErrors(e=>({...e,[k]:''}));}
  function validate(){const e:Record<string,string>={};if(!draft.code.trim())e.code='Informe o código interno.';if(!draft.description.trim())e.description='Informe a descrição.';if(!draft.ownerCompanyId)e.ownerCompanyId='Selecione a empresa proprietária.';if(draft.periodicityMonths!==null&&(!Number.isInteger(draft.periodicityMonths)||draft.periodicityMonths<1))e.periodicityMonths='Use meses inteiros positivos ou deixe pendente.';if(initial.periodicityMonths!==draft.periodicityMonths && (!reason.trim() || !evidence.trim()))e.reason='Alteração da periodicidade exige motivo e evidência.';if(draft.capabilities.some(c=>!c.quantity.trim()||!c.unit.trim()||!decimal(c.min)||!decimal(c.max)||decimal(c.min)!.gt(decimal(c.max)!)))e.capabilities='Cada faixa precisa de grandeza, unidade e limites válidos (mínimo ≤ máximo).';return e;}
  const input=(key:keyof Instrument,label:string,required=false)=><Field key={key} label={label} error={errors[key]}><input list={['type','area','sector','process','location'].includes(key)?`catalog-${key}`:undefined} value={String(draft[key]??'')} required={required} aria-invalid={!!errors[key]} onChange={e=>set(key,e.target.value as never)}/>{['type','area','sector','process','location'].includes(key)&&<datalist id={`catalog-${key}`}>{catalogs.filter(c=>c.active&&c.kind===key as CatalogKind&&c.companyId===draft.ownerCompanyId).map(c=><option key={c.id} value={c.name}/>)}</datalist>}</Field>;
  return <form className="wizard" onSubmit={async e=>{e.preventDefault();const found=validate();setErrors(found);if(Object.keys(found).length){setStep(found.code||found.description?0:found.ownerCompanyId?2:found.capabilities?1:3);return;}await onSave(draft,reason,evidence);}}>
    <Steps labels={['Identificação','Características','Uso e responsabilidade','Controle metrológico','Documentos']} step={step}/>
    <section className="wizard-body"><h3>{['Identificações independentes','Características e grandezas','Uso e responsabilidade','Plano de controle','Documentos e revisão do cadastro'][step]}</h3>
    {step===0&&<div className="form-grid">{input('code','Código interno RHDD',true)}{input('description','Descrição',true)}{input('tag','TAG')}{input('serial','Número de série do fabricante')}{input('internalId','Identificação interna')}{input('assetNumber','Patrimônio')}{input('liNumber','Número LI / N-1710')}</div>}
    {step===1&&<><div className="form-grid">{input('type','Tipo / família')}{input('manufacturer','Fabricante')}{input('model','Modelo')}<Field label="Criticidade" hint="Definição RHDD pendente; sem classificação automática."><input value={draft.criticality} onChange={e=>set('criticality',e.target.value)}/></Field></div><h4>Grandezas e faixas</h4>{errors.capabilities&&<p className="error">{errors.capabilities}</p>}{draft.capabilities.map((c,index)=><div className="range-row" key={c.id}>{(['quantity','unit','min','max','rangeType'] as const).map((k,i)=><Field key={k} label={['Grandeza','Unidade','Mínimo','Máximo','Tipo de faixa'][i]}><input value={c[k]} onChange={e=>set('capabilities',draft.capabilities.map((v,j)=>j===index?{...v,[k]:e.target.value}:v))}/></Field>)}<button type="button" className="text-button" onClick={()=>set('capabilities',draft.capabilities.filter(x=>x.id!==c.id))}>Remover faixa</button></div>)}<button type="button" className="secondary" onClick={()=>set('capabilities',[...draft.capabilities,{id:crypto.randomUUID(),quantity:'',unit:'',min:'',max:'',rangeType:'faixa de indicação'}])}>Adicionar grandeza / faixa</button></>}
    {step===2&&<div className="form-grid"><Field label="Empresa proprietária" error={errors.ownerCompanyId}><select value={draft.ownerCompanyId} aria-invalid={!!errors.ownerCompanyId} onChange={e=>set('ownerCompanyId',e.target.value)}><option value="">Selecione</option>{companies.filter(c=>c.active).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="Empresa usuária"><select value={draft.userCompanyId} onChange={e=>set('userCompanyId',e.target.value)}><option value="">Configuração pendente</option>{companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field>{input('area','Área')}{input('sector','Setor')}{input('process','Processo')}{input('location','Local de uso')}{input('responsible','Responsável')}</div>}
    {step===3&&<><div className="form-grid"><Field label="Tipo de controle"><select value={draft.controlType} onChange={e=>set('controlType',e.target.value as Instrument['controlType'])}><option value="">Configuração RHDD pendente</option><option>calibração externa</option><option>verificação interna</option></select></Field><Field label="Periodicidade (meses)" error={errors.periodicityMonths} hint="Não há frequência padrão. A próxima data será confirmada em cada evento."><input type="number" min="1" step="1" value={draft.periodicityMonths??''} onChange={e=>set('periodicityMonths',e.target.value?Number(e.target.value):null)} aria-invalid={!!errors.periodicityMonths}/></Field><Field label="Status cadastral"><select value={draft.registrationStatus} onChange={e=>set('registrationStatus',e.target.value as Instrument['registrationStatus'])}>{['ativo','inativo','desmobilizado','baixado'].map(x=><option key={x}>{x}</option>)}</select></Field></div>{initial.periodicityMonths!==draft.periodicityMonths&&<div className="notice"><h4>Registrar mudança de periodicidade</h4><p>Anterior: {initial.periodicityMonths??'pendente'} → novo: {draft.periodicityMonths??'pendente'} meses</p><div className="form-grid"><Field label="Motivo" error={errors.reason}><textarea value={reason} aria-invalid={!!errors.reason} onChange={e=>setReason(e.target.value)}/></Field><Field label="Evidência / referência"><input value={evidence} aria-invalid={!!errors.reason} onChange={e=>setEvidence(e.target.value)}/></Field></div></div>}<p className="muted">Situação operacional: <strong>{draft.operationalStatus}</strong>. A liberação será registrada na decisão metrológica.</p></>}
    {step===4&&<><div className="notice">Após salvar, abra a ficha para anexar fotos e documentos gerais. Certificados são anexados no evento de calibração/verificação, preservando cada ciclo.</div><Field label="Observações"><textarea value={draft.notes} onChange={e=>set('notes',e.target.value)}/></Field><dl className="review-summary"><div><dt>Código</dt><dd>{draft.code||'Pendente'}</dd></div><div><dt>Descrição</dt><dd>{draft.description||'Pendente'}</dd></div><div><dt>Empresa</dt><dd>{companies.find(c=>c.id===draft.ownerCompanyId)?.name||'Pendente'}</dd></div><div><dt>Periodicidade</dt><dd>{draft.periodicityMonths?`${draft.periodicityMonths} meses`:'Configuração RHDD pendente'}</dd></div></dl></>}
    </section><footer className="wizard-footer"><button type="button" className="secondary" onClick={onCancel} disabled={busy}>Cancelar</button><div>{step>0&&<button type="button" className="secondary" onClick={()=>setStep(s=>s-1)} disabled={busy}>Voltar</button>}{step<4?<button key="continue" type="button" className="primary" onClick={e=>{e.preventDefault();setStep(s=>s+1);}}>Continuar</button>:<button key="save" type="submit" className="primary" disabled={busy}>{busy?'Salvando…':'Salvar instrumento'}</button>}</div></footer>
  </form>;
}
