import {useEffect,useMemo,useRef,useState} from 'react';
import type {Company} from '../domain/types';
import {buildPreview,importFields,mappingErrors,normalizeCode,suggestMapping,type ImportMapping,type ImportResult,type PreviewRow,type SheetData} from '../domain/li-import';
import {Badge,Field,Steps} from './Primitives';
interface Batch {id:string;rows:PreviewRow[];result?:ImportResult}
interface Job {companyId:string;sourceName:string;batches:Batch[]}
export default function LIImporter({companies,checkCodes,onImport,onComplete}:{companies:Company[];checkCodes:(codes:string[])=>Promise<string[]>;onImport:(rows:PreviewRow[],companyId:string,sourceName:string,batchId:string)=>Promise<ImportResult>;onComplete:()=>void}){
 const [step,setStep]=useState(0),[file,setFile]=useState<File|null>(null),[sheet,setSheet]=useState<SheetData|null>(null),[sheetName,setSheetName]=useState(''),[headerRow,setHeaderRow]=useState(1),[company,setCompany]=useState(''),[mapping,setMapping]=useState<ImportMapping>({}),[known,setKnown]=useState<string[]>([]),[excluded,setExcluded]=useState<Set<number>>(new Set()),[busy,setBusy]=useState(false),[error,setError]=useState(''),[confirmed,setConfirmed]=useState(false),[progress,setProgress]=useState(''),[results,setResults]=useState<ImportResult[]>([]),[frozen,setFrozen]=useState(false);
 const job=useRef<Job|null>(null),worker=useRef<Worker|null>(null);
 useEffect(()=>()=>worker.current?.terminate(),[]);
 const preview=useMemo(()=>buildPreview(sheet?.rows||[],mapping,company,known),[sheet,mapping,company,known]);
 const ready=preview.filter(r=>r.status==='ready'&&!excluded.has(r.rowNumber));
 const duplicate=preview.filter(r=>r.status==='duplicate').length,invalid=preview.filter(r=>r.status==='invalid').length;
 async function read(){if(!file){setError('Selecione uma planilha.');return;}if(file.size>20*1024*1024||!file.size||! /\.(xlsx|xls|csv)$/i.test(file.name)){setError('Use XLSX, XLS ou CSV de até 20 MB.');return;}setBusy(true);setError('');try{
  const buffer=await file.arrayBuffer();const w=new Worker(new URL('../workers/li-reader.ts',import.meta.url),{type:'module'});worker.current=w;
  const parsed=await new Promise<SheetData>((resolve,reject)=>{const timer=setTimeout(()=>{w.terminate();reject(new Error('A leitura excedeu o tempo permitido. Divida a planilha em partes menores.'));},30000);w.onmessage=e=>{clearTimeout(timer);w.terminate();if(e.data.error)reject(new Error(e.data.error));else resolve(e.data.data);};w.onerror=()=>{clearTimeout(timer);w.terminate();reject(new Error('Não foi possível ler a planilha. Verifique o formato.'));};w.postMessage({buffer,sheet:sheetName||undefined,headerRow},[buffer]);});
  setSheet(parsed);setSheetName(parsed.sheet);setMapping(suggestMapping(parsed.headers));setKnown([]);setExcluded(new Set());setConfirmed(false);setStep(1);
 }catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function makePreview(){setError('');const errors=mappingErrors(mapping);if(!company)errors.push('Selecione a empresa proprietária.');if(errors.length){setError(errors.join(' '));return;}setBusy(true);try{const codes=sheet!.rows.map(r=>r.values[mapping.liNumber!]||'');setKnown(await checkCodes(Array.from(new Set(codes.map(normalizeCode)))));setExcluded(new Set());setConfirmed(false);setStep(2);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function commit(){setError('');if(!job.current){if(!confirmed||!ready.length){setError('Revise e confirme as linhas selecionadas.');return;}job.current={companyId:company,sourceName:file!.name.slice(0,255),batches:[]};for(let i=0;i<ready.length;i+=500)job.current.batches.push({id:crypto.randomUUID(),rows:ready.slice(i,i+500)});setFrozen(true);}setBusy(true);
  try{const task=job.current;for(let i=0;i<task.batches.length;i++){const batch=task.batches[i];if(batch.result)continue;setProgress(`Registrando lote ${i+1} de ${task.batches.length}…`);batch.result=await onImport(batch.rows,task.companyId,task.sourceName,batch.id);setResults(task.batches.flatMap(b=>b.result?[b.result]:[]));}setProgress('Importação concluída.');setStep(3);onComplete();}catch(e){setError(`${(e as Error).message} Os lotes concluídos foram preservados. Use “Retomar importação” para repetir o lote pendente com a mesma referência.`);}finally{setBusy(false);}
 }
 function reset(){setStep(0);setFile(null);setSheet(null);setSheetName('');setHeaderRow(1);setKnown([]);setExcluded(new Set());setResults([]);setConfirmed(false);setError('');setProgress('');setFrozen(false);job.current=null;}
 function exportReview(){const outcomes=new Map(results.flatMap(r=>r.rows.map(x=>[x.rowNumber,x.outcome] as const)));const rows=[['Linha','Número LI / N-1710','Descrição','Situação','Observações'],...preview.map(r=>[String(r.rowNumber),r.instrument.liNumber,r.instrument.description,outcomes.get(r.rowNumber)==='imported'?'Importado':outcomes.get(r.rowNumber)==='duplicate'?'Duplicado no cadastro':r.status==='invalid'?'Inválido':r.status==='duplicate'?'Duplicado':excluded.has(r.rowNumber)?'Não selecionado':'Pronto para importar',r.errors.join(' | ')])];const csv='\uFEFF'+rows.map(row=>row.map(v=>'"'+(/^[=+@-]/.test(v)?"'"+v:v).replaceAll('"','""')+'"').join(';')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='Metrikon_revisao_LI.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <section className="panel li-import"><Steps labels={['Arquivo','Mapeamento','Prévia e confirmação','Resultado']} step={step}/><p className="notice">A LI cria o cadastro. Cada novo instrumento inicia fora de uso; periodicidades e faixas só serão preenchidas quando informadas. A liberação depende da análise e decisão metrológica.</p>{error&&<div className="notice danger" role="alert">{error}</div>}{busy&&<p role="status">{progress||'Processando a planilha…'}</p>}
 {step===0&&<><div className="form-grid"><Field label="Planilha LI" hint="XLSX, XLS ou CSV, até 20 MB e 10.000 linhas. O arquivo é lido nesta sessão."><input type="file" accept=".xlsx,.xls,.csv" disabled={busy} onChange={e=>{setFile(e.target.files?.[0]||null);setSheetName('');}}/></Field><Field label="Linha do cabeçalho"><input type="number" min={1} max={30} value={headerRow} disabled={busy} onChange={e=>setHeaderRow(Number(e.target.value))}/></Field></div><button className="primary" disabled={busy||!file} onClick={read}>Ler planilha</button></>}
 {step===1&&sheet&&<><div className="form-grid"><Field label="Empresa proprietária da importação"><select value={company} disabled={busy} onChange={e=>setCompany(e.target.value)}><option value="">Selecione</option>{companies.filter(c=>c.active).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="Aba da planilha"><select value={sheetName} disabled={busy} onChange={e=>setSheetName(e.target.value)}>{sheet.sheets.map(s=><option key={s}>{s}</option>)}</select></Field><Field label="Linha do cabeçalho"><input type="number" min={1} max={30} value={headerRow} disabled={busy} onChange={e=>setHeaderRow(Number(e.target.value))}/></Field></div><button className="secondary" disabled={busy} onClick={read}>Reler aba e cabeçalho</button><h3>Correspondência das colunas</h3><p className="muted">Confira as colunas da LI. Para o cadastro, o Metrikon usa apenas os campos que existem na ficha de referência. Número LI / N-1710 e Equipamento crítico são obrigatórios na importação.</p><div className="form-grid mapping-grid">{importFields.map(([field,label])=><Field key={field} label={label+(field==='liNumber'||field==='criticality'?' *':'')}><select disabled={busy} value={mapping[field]??''} onChange={e=>setMapping({...mapping,[field]:e.target.value===''?undefined:Number(e.target.value)})}><option value="">Não importar</option>{sheet.headers.map((h,i)=><option key={i} value={i}>{i+1}. {h}</option>)}</select></Field>)}</div><div className="table-wrap"><table><caption>Amostra das primeiras 5 linhas · {sheet.rows.length} linhas no arquivo</caption><thead><tr><th>Linha</th>{sheet.headers.map((h,i)=><th key={i}>{h}</th>)}</tr></thead><tbody>{sheet.rows.slice(0,5).map(r=><tr key={r.rowNumber}><td>{r.rowNumber}</td>{sheet.headers.map((_,i)=><td key={i}>{r.values[i]}</td>)}</tr>)}</tbody></table></div><div className="import-actions"><button className="secondary" disabled={busy} onClick={()=>setStep(0)}>Trocar arquivo</button><button className="primary" disabled={busy} onClick={makePreview}>Gerar prévia</button></div></>}
 {(step===2||step===3)&&<><div className="import-summary"><Badge>{ready.length} selecionados</Badge><Badge>{duplicate} duplicados</Badge><Badge>{invalid} inválidos</Badge><span>Empresa: {companies.find(c=>c.id===company)?.name}</span></div><p className="muted">Números LI já cadastrados e repetidos na planilha são ignorados. Corrija linhas inválidas na origem e importe um novo arquivo. A prévia exibe as primeiras 200 linhas; a seleção inicial inclui todas as linhas válidas.</p><div className="table-wrap"><table><thead><tr><th>Selecionar</th><th>Linha</th><th>Número LI / N-1710</th><th>Equipamento / identificação</th><th>Situação</th><th>Observações</th></tr></thead><tbody>{preview.slice(0,200).map(r=><tr key={r.rowNumber}><td><input type="checkbox" aria-label={`Importar linha ${r.rowNumber}`} checked={r.status==='ready'&&!excluded.has(r.rowNumber)} disabled={busy||frozen||r.status!=='ready'} onChange={e=>{const next=new Set(excluded);if(e.target.checked)next.delete(r.rowNumber);else next.add(r.rowNumber);setExcluded(next);setConfirmed(false);}}/></td><td>{r.rowNumber}</td><td>{r.instrument.liNumber||'—'}</td><td>{r.instrument.criticality||'—'}<small className="block">Série: {r.instrument.serial||'—'} · Modelo: {r.instrument.model||'—'}</small></td><td><Badge>{r.status==='ready'?'Válido':r.status==='duplicate'?'Duplicado':'Inválido'}</Badge></td><td>{r.errors.join(' ')||'Cadastro sem liberação operacional'}</td></tr>)}</tbody></table></div><div className="import-actions"><button className="secondary" onClick={exportReview}>Exportar revisão CSV</button>{step===2&&!frozen&&<button className="secondary" disabled={busy} onClick={()=>setStep(1)}>Voltar ao mapeamento</button>}</div>
 {step===2&&<><label className="import-confirm"><input type="checkbox" checked={confirmed} disabled={busy||frozen} onChange={e=>setConfirmed(e.target.checked)}/>Revisei o mapeamento, a empresa e as {ready.length} linhas selecionadas. Confirmo a criação dos cadastros.</label><button className="primary" disabled={busy||(!frozen&&(!confirmed||!ready.length))} onClick={commit}>{frozen?'Retomar importação':`Confirmar importação de ${ready.length} instrumentos`}</button></>}
 {step===3&&<div className="notice success" role="status"><strong>Importação concluída: {results.reduce((n,r)=>n+r.created,0)} criados, {results.reduce((n,r)=>n+r.skipped,0)} duplicados preservados.</strong><p>As linhas e a origem foram registradas no histórico. Revise cada ficha antes do primeiro controle.</p><button className="secondary" onClick={reset}>Nova importação</button></div>}</>}
 </section>;
}
