import {useMemo,useState} from 'react';
import type {Company} from '../domain/types';
import {certificateErrors,newLaboratory,newStandard,newStandardCertificate,type Laboratory,type ReferenceStandard,type StandardCertificate,type TraceabilityData} from '../domain/traceability';
import {Badge,Empty,Field,Modal} from './Primitives';

interface Props {
 data:TraceabilityData; companies:Company[]; canEdit:boolean; loading:boolean; loadError:string;
 onSaveLaboratory:(lab:Laboratory)=>Promise<void>; onSaveStandard:(standard:ReferenceStandard)=>Promise<void>;
 onSaveCertificate:(cert:StandardCertificate,file?:File)=>Promise<void>; onOpen:(path:string)=>Promise<void>;
}
export default function TraceabilityManager({data,companies,canEdit,loading,loadError,onSaveLaboratory,onSaveStandard,onSaveCertificate,onOpen}:Props){
 const [tab,setTab]=useState<'laboratories'|'standards'>('laboratories'),[company,setCompany]=useState(''),[search,setSearch]=useState(''),[page,setPage]=useState(0);
 const [lab,setLab]=useState<Laboratory|null>(null),[standard,setStandard]=useState<ReferenceStandard|null>(null),[selectedId,setSelectedId]=useState('');
 const [certificate,setCertificate]=useState<StandardCertificate|null>(null),[file,setFile]=useState<File|undefined>(),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const needle=search.trim().toLocaleLowerCase('pt-BR');
 const labs=useMemo(()=>data.laboratories.filter(l=>(!company||l.companyId===company)&&(!needle||[l.name,l.cnpj,l.scope,l.accreditationReference].join(' ').toLocaleLowerCase('pt-BR').includes(needle))),[data.laboratories,company,needle]);
 const standards=useMemo(()=>data.standards.filter(s=>(!company||s.companyId===company)&&(!needle||[s.name,s.serial,s.model,s.quantity].join(' ').toLocaleLowerCase('pt-BR').includes(needle))),[data.standards,company,needle]);
 const rows=tab==='laboratories'?labs:standards;const selected=data.standards.find(s=>s.id===selectedId);
 const certificates=data.certificates.filter(c=>c.standardId===selectedId).sort((a,b)=>b.version-a.version);
 const companyName=(id:string)=>companies.find(c=>c.id===id)?.name||'Empresa indisponível';
 function close(){if(!busy){setLab(null);setStandard(null);setCertificate(null);setFile(undefined);setError('');}}
 async function save(action:()=>Promise<void>){setBusy(true);setError('');try{await action();setLab(null);setStandard(null);setCertificate(null);setFile(undefined);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function changeTab(next:'laboratories'|'standards'){setTab(next);setPage(0);setSelectedId('');setError('');}
 const companyField=(id:string,locked:boolean,onChange:(id:string)=>void)=><Field label="Empresa do vínculo *"><select required disabled={locked||busy} value={id} onChange={e=>onChange(e.target.value)}><option value="">Selecione</option>{companies.filter(c=>c.active||c.id===id).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field>;
 return <section className="panel traceability-manager">
  <div className="panel-head"><div><h2>Laboratórios e padrões</h2><p>Cadastros e certificados por empresa. Cada calibração preserva as referências utilizadas.</p></div></div>
  <div className="trace-tabs" role="group" aria-label="Cadastros de rastreabilidade"><button className={tab==='laboratories'?'primary':'secondary'} aria-pressed={tab==='laboratories'} onClick={()=>changeTab('laboratories')}>Laboratórios</button><button className={tab==='standards'?'primary':'secondary'} aria-pressed={tab==='standards'} onClick={()=>changeTab('standards')}>Padrões</button></div>
  <div className="form-grid"><Field label="Filtrar empresa"><select value={company} onChange={e=>{setCompany(e.target.value);setPage(0);setSelectedId('');}}><option value="">Todas as empresas</option>{companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="Pesquisar laboratório ou padrão"><input value={search} onChange={e=>{setSearch(e.target.value);setPage(0);}}/></Field></div>
  {loadError&&<div className="notice danger" role="alert">{loadError}</div>}
  {loading&&<p role="status">Carregando laboratórios, padrões e certificados…</p>}
  {canEdit&&<button className="primary" disabled={loading||!!loadError} onClick={()=>{setError('');if(tab==='laboratories')setLab(newLaboratory(company));else setStandard(newStandard(company));}}>{tab==='laboratories'?'Novo laboratório':'Novo padrão'}</button>}
  {!loading&&!rows.length?<Empty>Nenhum {tab==='laboratories'?'laboratório':'padrão'} encontrado.</Empty>:<div className="trace-cards">{tab==='laboratories'?labs.slice(page*50,page*50+50).map(l=><article className="trace-card" key={l.id}><div className="section-title"><h3>{l.name}</h3><Badge>{l.active?'ativo':'inativo'}</Badge></div><p>{companyName(l.companyId)} · {l.cnpj||'CNPJ não informado'}</p><dl className="trace-info"><div><dt>Acreditação informada</dt><dd>{l.accreditation||'não informada'} · {l.accreditationReference||'referência pendente'}</dd></div><div><dt>Escopo</dt><dd>{l.scope||'não informado'}</dd></div><div><dt>Período da acreditação</dt><dd>{l.validFrom||'início pendente'} → {l.validUntil||'fim pendente'}</dd></div><div><dt>Contato</dt><dd>{l.contact||'não informado'}</dd></div></dl>{canEdit&&<button className="secondary" onClick={()=>{setError('');setLab({...l});}}>Editar laboratório {l.name}</button>}</article>):standards.slice(page*50,page*50+50).map(s=><article className="trace-card" key={s.id}><div className="section-title"><h3>{s.name}</h3><Badge>{s.active?'ativo':'inativo'}</Badge></div><p>{companyName(s.companyId)} · {s.serial} · {s.model||'modelo não informado'}</p><p>{s.quantity||'grandeza não informada'} · {s.range||'faixa não informada'} {s.unit}</p><div className="trace-actions"><button className="secondary" onClick={()=>{setSelectedId(s.id);setError('');}}>Certificados de {s.serial}</button>{canEdit&&<button className="text-button" onClick={()=>{setError('');setStandard({...s});}}>Editar padrão {s.serial}</button>}</div></article>)}</div>}
  {rows.length>50&&<footer className="pagination"><span>{page*50+1}–{Math.min(page*50+50,rows.length)} de {rows.length}</span><div><button className="secondary" disabled={page===0} onClick={()=>setPage(p=>p-1)}>Anterior</button><button className="secondary" disabled={(page+1)*50>=rows.length} onClick={()=>setPage(p=>p+1)}>Próxima</button></div></footer>}
  {selected&&<section className="asset-section"><div className="section-title"><div><h3>Certificados do padrão: {selected.name}</h3><p>{selected.serial} · {companyName(selected.companyId)}</p></div>{canEdit&&<button className="primary" onClick={()=>{setError('');setFile(undefined);setCertificate(newStandardCertificate(selected));}}>Novo certificado do padrão</button>}</div><p className="notice">Cada certificado é uma versão permanente. Para renovar ou corrigir, registre outro certificado. A validade é informada conforme a evidência, sem periodicidade presumida.</p>{certificates.length?<div className="trace-cards">{certificates.map(c=><article className="trace-card" key={c.id}><div className="section-title"><h4>{c.number} · versão {c.version}</h4><Badge>{c.validUntil?'Validade registrada':'validade não informada'}</Badge></div><p>Emissor: {c.issuer} · Calibração: {c.calibrationDate} · Validade: {c.validUntil||'não informada'}</p><p>Escopo: {c.scope||'não informado'}</p><p>Rastreabilidade: {c.traceabilityEvidence||'não informada'}</p>{c.supersedesId&&<p>Substitui: {data.certificates.find(previous=>previous.id===c.supersedesId)?.number||c.supersedesId}. O registro anterior permanece preservado.</p>}{c.attachmentPath?<button className="secondary" disabled={busy} onClick={async()=>{setError('');try{await onOpen(c.attachmentPath);}catch(e){setError((e as Error).message);}}}>Abrir certificado {c.number}</button>:<p className="muted">Sem arquivo anexado.</p>}</article>)}</div>:<Empty>Nenhum certificado do padrão registrado.</Empty>}{error&&!lab&&!standard&&!certificate&&<p className="error" role="alert">{error}</p>}</section>}
  {(lab||standard)&&<Modal title={lab?'Cadastro de laboratório':'Cadastro de padrão'} onClose={close} wide><form className="wizard" onSubmit={e=>{e.preventDefault();if(lab)save(()=>onSaveLaboratory(lab));else if(standard)save(()=>onSaveStandard(standard));}}><div className="wizard-body"><p className="notice">Inativar preserva certificados e vínculos históricos.</p><div className="form-grid">
   {lab&&<>{companyField(lab.companyId,data.laboratories.some(l=>l.id===lab.id),id=>setLab({...lab,companyId:id}))}<Field label="Nome do laboratório *"><input required maxLength={200} value={lab.name} onChange={e=>setLab({...lab,name:e.target.value})}/></Field><Field label="CNPJ"><input maxLength={30} value={lab.cnpj} onChange={e=>setLab({...lab,cnpj:e.target.value})}/></Field><Field label="Contato"><input maxLength={500} value={lab.contact} onChange={e=>setLab({...lab,contact:e.target.value})}/></Field><Field label="Acreditação informada"><select value={lab.accreditation} onChange={e=>setLab({...lab,accreditation:e.target.value as Laboratory['accreditation']})}><option value="">Não informada</option><option value="sim">sim</option><option value="não">não</option></select></Field><Field label="Referência da acreditação"><input maxLength={500} value={lab.accreditationReference} onChange={e=>setLab({...lab,accreditationReference:e.target.value})}/></Field><Field label="Início da acreditação"><input type="date" value={lab.validFrom} onChange={e=>setLab({...lab,validFrom:e.target.value})}/></Field><Field label="Fim da acreditação"><input type="date" min={lab.validFrom||undefined} value={lab.validUntil} onChange={e=>setLab({...lab,validUntil:e.target.value})}/></Field><Field label="Escopo do laboratório"><textarea maxLength={5000} value={lab.scope} onChange={e=>setLab({...lab,scope:e.target.value})}/></Field><Field label="Observações do laboratório"><textarea maxLength={2000} value={lab.notes} onChange={e=>setLab({...lab,notes:e.target.value})}/></Field><Field label="Situação do laboratório"><select value={lab.active?'ativo':'inativo'} onChange={e=>setLab({...lab,active:e.target.value==='ativo'})}><option>ativo</option><option>inativo</option></select></Field></>}
   {standard&&<>{companyField(standard.companyId,data.standards.some(s=>s.id===standard.id),id=>setStandard({...standard,companyId:id}))}<Field label="Nome do padrão *"><input required maxLength={200} value={standard.name} onChange={e=>setStandard({...standard,name:e.target.value})}/></Field><Field label="Série / identificação do padrão *"><input required maxLength={200} value={standard.serial} onChange={e=>setStandard({...standard,serial:e.target.value})}/></Field>{(['model','quantity','range','unit'] as const).map((key,index)=><Field key={key} label={['Modelo do padrão','Grandeza do padrão','Faixa do padrão','Unidade do padrão'][index]}><input maxLength={500} value={standard[key]} onChange={e=>setStandard({...standard,[key]:e.target.value})}/></Field>)}<Field label="Observações do padrão"><textarea maxLength={2000} value={standard.notes} onChange={e=>setStandard({...standard,notes:e.target.value})}/></Field><Field label="Situação do padrão"><select value={standard.active?'ativo':'inativo'} onChange={e=>setStandard({...standard,active:e.target.value==='ativo'})}><option>ativo</option><option>inativo</option></select></Field></>}
  </div>{error&&<div className="notice danger" role="alert">{error}</div>}</div><footer className="wizard-footer"><button type="button" className="secondary" disabled={busy} onClick={close}>Cancelar</button><button className="primary" disabled={busy}>{busy?'Salvando…':lab?'Salvar laboratório':'Salvar padrão'}</button></footer></form></Modal>}
  {certificate&&<Modal title="Novo certificado do padrão" onClose={close} wide><form className="wizard" onSubmit={e=>{e.preventDefault();const errors=certificateErrors(certificate);if(errors.length){setError(errors.join(' '));return;}save(()=>onSaveCertificate(certificate,file));}}><div className="wizard-body"><div className="form-grid"><Field label="Número do certificado do padrão *"><input required maxLength={200} value={certificate.number} onChange={e=>setCertificate({...certificate,number:e.target.value})}/></Field><Field label="Entidade emissora do padrão *"><input required maxLength={500} value={certificate.issuer} onChange={e=>setCertificate({...certificate,issuer:e.target.value})}/></Field><Field label="Vincular laboratório emissor"><select value={certificate.issuerLaboratoryId} onChange={e=>setCertificate({...certificate,issuerLaboratoryId:e.target.value})}><option value="">Sem vínculo cadastral</option>{data.laboratories.filter(l=>l.companyId===certificate.companyId&&l.active).map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></Field><Field label="Data da calibração do padrão *"><input required type="date" value={certificate.calibrationDate} onChange={e=>setCertificate({...certificate,calibrationDate:e.target.value})}/></Field><Field label="Validade do certificado do padrão" hint="Informe a validade comprovada. Sem data, a validade permanece não informada."><input type="date" min={certificate.calibrationDate||undefined} value={certificate.validUntil} onChange={e=>setCertificate({...certificate,validUntil:e.target.value})}/></Field><Field label="Certificado anterior substituído"><select value={certificate.supersedesId} onChange={e=>setCertificate({...certificate,supersedesId:e.target.value})}><option value="">Nenhum</option>{certificates.map(c=><option key={c.id} value={c.id}>{c.number} · versão {c.version}</option>)}</select></Field><Field label="Escopo do certificado do padrão"><textarea maxLength={5000} value={certificate.scope} onChange={e=>setCertificate({...certificate,scope:e.target.value})}/></Field><Field label="Evidência de rastreabilidade do padrão"><textarea maxLength={5000} value={certificate.traceabilityEvidence} onChange={e=>setCertificate({...certificate,traceabilityEvidence:e.target.value})}/></Field><Field label="Arquivo do certificado do padrão" hint="PDF, XLSX ou XLS, até 16 MB. O anexo será permanente e privado."><input type="file" accept=".pdf,.xlsx,.xls" onChange={e=>setFile(e.target.files?.[0])}/></Field></div>{error&&<div className="notice danger" role="alert">{error}</div>}</div><footer className="wizard-footer"><button type="button" className="secondary" disabled={busy} onClick={close}>Cancelar</button><button className="primary" disabled={busy}>{busy?'Registrando…':'Registrar certificado do padrão'}</button></footer></form></Modal>}
 </section>;
}
