import {useEffect,useState} from 'react';
import {Activity,AlertTriangle,ArrowRight,CheckCircle2,ClipboardList,Clock,Download,Gauge,RefreshCw,ShieldCheck} from 'lucide-react';
import type {Session} from '@supabase/supabase-js';
import {configurationError,supabase} from './services/supabase';
import * as repository from './services/repository';
import * as minimal from './services/minimal-repository';
import {demoState} from './services/demo';
import {emptyInstrument,emptyEvent,daysUntil} from './domain/metrology';
import type {Company,Instrument,LIReferenceSummary,MetrologicalEvent} from './domain/types';
import {evaluateSimple,newCertificate,monitoringStatus,roleLabels,simpleErrors,isRenewal,type SimpleRegistration,type SimpleCertificate,type Member} from './domain/minimal';
import {Badge,Empty,Field,Modal} from './components/Primitives';
import SimpleRegistrationForm from './components/SimpleRegistrationForm';

const permissionsFor=(role:string)=>role==='owner'?['read','edit_registration','review_registration','manage_access']:role==='quality_admin'?['read','edit_registration','review_registration']:role==='analyst'?['read','edit_registration']:['read'];
const authErrorMessage=(message:string)=>{const value=message.toLocaleLowerCase('pt-BR');if(value.includes('invalid login credentials'))return 'E-mail ou senha incorretos.';if(value.includes('email not confirmed'))return 'Confirme seu e-mail para continuar.';if(value.includes('failed to fetch')||value.includes('network')||value.includes('fetch'))return 'Não foi possível conectar ao serviço. Tente novamente.';return 'Não foi possível entrar. Confira os dados e tente novamente.';};
const emptyWorkspace: minimal.Workspace={items:[],total:0,metrics:{total:0,expired:0,soon:0,pending:0}};
const fmt=(date:string)=>date?/^\d{4}-\d{2}-\d{2}$/.test(date)?date.split('-').reverse().join('/'):date:'—';
const localToday=()=>new Date().toLocaleDateString('en-CA',{timeZone:'America/Recife'});
const deadlineCopy=(instrument:Instrument)=>{const days=daysUntil(instrument.nextControl,localToday());if(days===null)return 'Sem vencimento informado';if(days<0){const n=Math.abs(days);return 'Vencido há '+n+' '+(n===1?'dia':'dias');}if(days===0)return 'Vence hoje';return 'Vence em '+days+' '+(days===1?'dia':'dias');};
function draftFor(i:Instrument,c?:SimpleCertificate):SimpleRegistration{return {id:crypto.randomUUID(),instrumentId:i.id,companyId:i.ownerCompanyId,version:0,state:'rascunho',instrument:{...i},certificate:c?{...newCertificate(i.id),...c}:newCertificate(i.id),renewal:Boolean(i.lastControl),createdBy:'',submittedAt:'',reviewedBy:'',reviewedAt:'',reviewNotes:'',quantitative:{status:'pendente',total:'',operator:'<='}};}
export default function App(){
 const [mode,setMode]=useState<'demo'|'cloud'|null>(null),[session,setSession]=useState<Session|null>(null),[role,setRole]=useState('viewer'),[permissions,setPermissions]=useState<string[]>([]),[tab,setTab]=useState<'cadastro'|'monitoramento'>('monitoramento');
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false);
 const [search,setSearch]=useState(''),[query,setQuery]=useState(''),[filter,setFilter]=useState('todos'),[windowDays,setWindowDays]=useState(30),[page,setPage]=useState(0),[revision,setRevision]=useState(0),[workspace,setWorkspace]=useState<minimal.Workspace>(emptyWorkspace);
 const [companies,setCompanies]=useState<Company[]>([]),[li,setLI]=useState<LIReferenceSummary|null>(null),[scope,setScope]=useState<string|null>(null),[edit,setEdit]=useState<SimpleRegistration|null>(null),[detail,setDetail]=useState<Instrument|null>(null),[history,setHistory]=useState<SimpleRegistration[]>([]),[legacy,setLegacy]=useState<MetrologicalEvent[]>([]),[historyLoading,setHistoryLoading]=useState(false);
 const [demoInstruments,setDemoInstruments]=useState<Instrument[]>([]),[demoRecords,setDemoRecords]=useState<SimpleRegistration[]>([]),[demoFiles]=useState(()=>new Map<string,File>()),[access,setAccess]=useState(false),[members,setMembers]=useState<Member[]>([]),[memberEmail,setMemberEmail]=useState(''),[memberRole,setMemberRole]=useState('analyst'),[memberCompany,setMemberCompany]=useState(''),[memberEnabled,setMemberEnabled]=useState(true),[accessError,setAccessError]=useState('');
 const can=(p:string)=>permissions.includes(p);
 const applyMetric=(targetTab:'cadastro'|'monitoramento',targetFilter:string)=>{setTab(targetTab);setFilter(targetFilter);setPage(0);setSearch('');setError('');setNotice('');};
 useEffect(()=>{document.title='Metrikon';if(!supabase)return;let alive=true;supabase.auth.getSession().then(({data,error})=>{if(!alive)return;if(error)setError(error.message);else if(data.session){setSession(data.session);setMode('cloud');}});const {data:{subscription}}=supabase.auth.onAuthStateChange((_,s)=>{if(!alive)return;setSession(s);if(s)setMode('cloud');});return()=>{alive=false;subscription.unsubscribe();};},[]);
 useEffect(()=>{const id=setTimeout(()=>{setQuery(search.trim().slice(0,150));setPage(0);},250);return()=>clearTimeout(id);},[search]);
 useEffect(()=>{if(mode!=='cloud')return;let alive=true;setLoading(true);setError('');Promise.all([minimal.context(),repository.getCompanies(),repository.getLIReference(),minimal.workspace(query,filter,windowDays,page)]).then(([ctx,c,ref,w])=>{if(!alive)return;setRole(ctx.role);setScope(ctx.companyId);setPermissions(ctx.permissions);setCompanies(c);setLI(ref);setWorkspace(w);}).catch(e=>{if(alive){setWorkspace(emptyWorkspace);setPermissions([]);setError(e.message);}}).finally(()=>{if(alive)setLoading(false);});return()=>{alive=false;};},[mode,query,filter,windowDays,page,revision]);
 useEffect(()=>{if(mode!=='cloud')return;const id=setInterval(()=>{if(document.visibilityState==='visible')setRevision(v=>v+1);},30000);return()=>clearInterval(id);},[mode]);
 useEffect(()=>{if(mode!=='demo')return;const rows=demoInstruments.map(instrument=>({instrument,openRegistration:demoRecords.find(r=>r.instrumentId===instrument.id&&r.state!=='aprovado')||null}));const date=new Date().toLocaleDateString('en-CA',{timeZone:'America/Recife'});const soon=(i:Instrument)=>{const d=daysUntil(i.nextControl,date);return d!==null&&d>=0&&d<=windowDays;};const expired=(i:Instrument)=>(daysUntil(i.nextControl,date)??0)<0;
 const matches=rows.filter(r=>[r.instrument.liNumber,r.instrument.serial,r.instrument.criticality,r.instrument.location].join(' ').toLocaleLowerCase('pt-BR').includes(query.toLocaleLowerCase('pt-BR'))).filter(r=>filter==='todos'||filter==='proximos'&&soon(r.instrument)||filter==='vencidos'&&expired(r.instrument)||filter==='sem_data'&&!r.instrument.nextControl||filter==='aprovacao'&&r.openRegistration?.state==='aguardando aprovação').sort((a,b)=>(a.instrument.nextControl||'9999').localeCompare(b.instrument.nextControl||'9999')||a.instrument.liNumber.localeCompare(b.instrument.liNumber));setWorkspace({items:matches.slice(page*50,page*50+50),total:matches.length,metrics:{total:rows.length,expired:rows.filter(r=>expired(r.instrument)).length,soon:rows.filter(r=>soon(r.instrument)).length,pending:rows.filter(r=>r.openRegistration?.state==='aguardando aprovação').length}});
 },[mode,demoInstruments,demoRecords,query,filter,windowDays,page]);
 function demonstration(){const data=demoState();setDemoInstruments(data.instruments);setCompanies(data.companies);setDemoRecords([]);setMode('demo');setRole('owner');setPermissions(permissionsFor('owner'));setScope(null);setLI({prefix:'CE-5290.00-22313-856-C1O-',document:'LI oficial',sourceName:'Demonstração',nextNumber:843,nextRow:850,nextCode:'CE-5290.00-22313-856-C1O-843'});setError('');}
 async function login(){if(!supabase){setError(configurationError?'O Metrikon não conseguiu inicializar os serviços necessários.':'Não foi possível iniciar a autenticação.');return;}setBusy(true);setError('');try{const {error}=await supabase.auth.signInWithPassword({email:email.trim(),password});if(error)throw error;setPassword('');}catch(e){setError(authErrorMessage((e as Error).message));}finally{setBusy(false);}}
 async function signup(){if(!supabase)return;setBusy(true);setError('');try{const {error}=await supabase.auth.signUp({email:email.trim(),password});if(error)throw error;setPassword('');setNotice('Confira o e-mail para confirmar o acesso. Depois, o proprietário precisa liberar seu perfil.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function logout(){if(mode==='cloud')await supabase?.auth.signOut();setSession(null);setMode(null);setWorkspace(emptyWorkspace);setPermissions([]);setDemoRecords([]);setDemoInstruments([]);demoFiles.clear();setEdit(null);setDetail(null);setAccess(false);setHistory([]);setLegacy([]);setEmail('');setPassword('');setError('');setNotice('');setSearch('');setQuery('');setPage(0);setFilter('todos');}
 function navigate(next:'cadastro'|'monitoramento'){setTab(next);setFilter('todos');setPage(0);setSearch('');setError('');setNotice('');}
 function start(){const company=companies.find(c=>c.id===scope&&c.active)||companies.find(c=>c.name.toUpperCase()==='CONSAG'&&c.active)||companies.find(c=>c.active);if(!company){setError('Empresa do espaço de trabalho indisponível.');return;}const i=emptyInstrument();i.ownerCompanyId=company.id;i.contractorEquipment='não';setEdit(draftFor(i));}
 async function openDetail(i:Instrument){setDetail(i);setHistory([]);setLegacy([]);setHistoryLoading(true);try{if(mode==='demo'){setHistory(demoRecords.filter(r=>r.instrumentId===i.id).sort((a,b)=>b.version-a.version));setLegacy(demoState().events.filter(e=>e.instrumentId===i.id));}else{const [h,l]=await Promise.all([minimal.history(i.id),repository.listEvents(i.id)]);setHistory(h);setLegacy(l);}}catch(e){setError((e as Error).message);}finally{setHistoryLoading(false);}}
 async function update(i:Instrument,open:SimpleRegistration|null){if(open){setEdit(open);return;}setBusy(true);try{const h=mode==='demo'?demoRecords.filter(r=>r.instrumentId===i.id):await minimal.history(i.id);const approved=h.filter(r=>r.state==='aprovado').sort((a,b)=>b.version-a.version)[0];const events=approved?[]:mode==='demo'?demoState().events.filter(e=>e.instrumentId===i.id):await repository.listEvents(i.id);const latest=events.filter(e=>e.workflow==='concluído').sort((a,b)=>b.date.localeCompare(a.date))[0];const cert=approved?.certificate||((i as Instrument&{currentCertificate?:SimpleCertificate}).currentCertificate)|| (latest?{...latest,standardsValidation:'',attachmentName:'',restrictionText:latest.restriction?.description||''}:undefined);setEdit(draftFor({...emptyInstrument(),...i},cert));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function save(record:SimpleRegistration,file:File|undefined,submit:boolean){setBusy(true);setNotice('');try{if(file)await repository.inspectCertificateAttachment(file);let saved:SimpleRegistration;
 if(mode==='cloud'){saved=await minimal.save(record,false);setEdit(saved);if(file){const path=await repository.uploadCertificate({...emptyEvent(saved.instrumentId),id:saved.id},file);saved={...saved,certificate:{...saved.certificate,attachmentPath:path,attachmentName:file.name}};}saved=await minimal.save(saved,submit);}
 else{let i=record.instrument;const existing=demoInstruments.find(x=>x.id===i.id);if(!existing){if(!li)throw new Error('LI indisponível.');i={...i,liNumber:li.nextCode,code:li.nextCode,liSource:{row:li.nextRow,number:li.nextNumber,code:li.nextCode,companyId:i.ownerCompanyId,origin:'new',values:[]}};setLI({...li,nextNumber:li.nextNumber+1,nextRow:li.nextRow+1,nextCode:li.prefix+String(li.nextNumber+1).padStart(3,'0')});setDemoInstruments(all=>[...all,i]);}
 const cert={...record.certificate};if(file){cert.attachmentPath=`${i.id}/${record.id}/${crypto.randomUUID()}.pdf`;cert.attachmentName=file.name;demoFiles.set(cert.attachmentPath,file);}if(submit){const errors=simpleErrors(i,cert);if(errors.length)throw new Error(errors.join(' '));}const prev=demoRecords.find(r=>r.id===record.id);if(prev&&['aprovado','aguardando aprovação'].includes(prev.state))throw new Error('Versão enviada é imutável.');saved={...record,instrument:i,certificate:cert,version:prev?.version||Math.max(0,...demoRecords.filter(r=>r.instrumentId===i.id).map(r=>r.version))+1,state:submit?'aguardando aprovação':'rascunho',createdBy:prev?.createdBy||'Equipe de demonstração',submittedAt:submit?new Date().toISOString():'',quantitative:evaluateSimple(cert)};setDemoRecords(all=>[...all.filter(r=>r.id!==saved.id),saved]);}
 setEdit(submit?null:saved);setRevision(v=>v+1);setNotice(submit?'Cadastro enviado. O responsável precisa aprovar para atualizar o certificado vigente.':'Rascunho salvo.');return saved;
 }finally{setBusy(false);}}
 async function review(approve:boolean,notes:string){if(!edit)return;setBusy(true);try{if(mode==='cloud')await minimal.review(edit.id,approve,notes);else{if(!can('review_registration'))throw new Error('Perfil sem aprovação.');const r={...edit,state:approve?'aprovado' as const:'devolvido' as const,reviewedBy:'Responsável de demonstração',reviewedAt:new Date().toISOString(),reviewNotes:notes};setDemoRecords(all=>all.map(x=>x.id===r.id?r:x));if(approve)setDemoInstruments(all=>all.map(x=>x.id===r.instrumentId?{...x,...r.instrument,lastControl:r.certificate.date,nextControl:r.certificate.nextDate,operationalStatus:r.certificate.decision||'fora de uso',currentCertificate:r.certificate,currentRegistrationId:r.id}:x));}setEdit(null);setRevision(v=>v+1);setNotice(approve?'Cadastro aprovado. Certificado vigente atualizado.':'Cadastro devolvido para correção.');}finally{setBusy(false);}}
 async function openFile(path:string){const windowRef=window.open('about:blank','_blank');if(windowRef)windowRef.opener=null;try{if(!windowRef)throw new Error('Permita abrir uma nova janela para visualizar o certificado.');if(mode==='cloud')windowRef.location.href=await repository.certificateUrl(path);else{const file=demoFiles.get(path);if(!file)throw new Error('Este certificado fictício não possui arquivo nesta sessão.');const url=URL.createObjectURL(file);windowRef.location.href=url;setTimeout(()=>URL.revokeObjectURL(url),60000);}}catch(e){windowRef?.close();setError((e as Error).message);}}
 async function exportList(){setBusy(true);try{let rows=workspace.items;if(mode==='cloud'){rows=[];for(let p=0;;p++){const batch=await minimal.workspace(query,filter,windowDays,p);rows.push(...batch.items);if(rows.length>=batch.total||!batch.items.length)break;}}else{rows=demoInstruments.map(instrument=>({instrument,openRegistration:null})).filter(r=>[r.instrument.liNumber,r.instrument.serial,r.instrument.criticality,r.instrument.location].join(' ').toLowerCase().includes(query.toLowerCase())).filter(r=>filter==='todos'||filter==='vencidos'&&monitoringStatus(r.instrument,windowDays)==='vencido'||filter==='proximos'&&monitoringStatus(r.instrument,windowDays)==='próximo do vencimento'||filter==='sem_data'&&!r.instrument.nextControl||filter==='aprovacao'&&demoRecords.some(x=>x.instrumentId===r.instrument.id&&x.state==='aguardando aprovação'));}
 const XLSX=await import('xlsx');const sheet=XLSX.utils.json_to_sheet(rows.map(({instrument:i})=>{const c=(i as Instrument&{currentCertificate?:SimpleCertificate}).currentCertificate;return {'Número LI':i.liNumber,'Linha LI':i.liSource?.row,'Obra':i.workSite,'Equipamento crítico':i.criticality,'Código de série / identificação':i.serial,'Modelo':i.model,'Local de uso':i.location,'Área/Setor responsável pela calibração do equipamento':i.calibrationResponsibleArea,'Processo':i.process,'Faixa de medição':i.measurementRange,'Faixa de utilização':i.usageRange,'Intervalo de calibrações (em meses)':i.periodicityMonths,'Valor da divisão de verificação do equipamento':i.verificationDivision,'Status do cadastro':i.registrationStatus,'Equipamento de empresa contratada?':i.contractorEquipment,'Data da calibração':i.lastControl,'Vencimento':i.nextControl,'Monitoramento':monitoringStatus(i,windowDays),'Situação do equipamento':i.operationalStatus,'Empresa contratada':i.contractorEquipment==='sim'?i.contractorCompanyName||'':'','Número do certificado':c?.certificateNumber||'','Laboratório acreditado?':c?.laboratoryAccredited||'','Padrões validados (rastreabilidade/validade)':c?.laboratoryAccredited==='não'?c.standardsValidation||'':'','Calibração aceita?':c?.calibrationAccepted||'','Aceito com restrição?':c?.acceptedWithRestriction||'','Restrição':c?.acceptedWithRestriction==='sim'?c.restrictionText||'':''};}));if(sheet['!ref'])sheet['!autofilter']={ref:sheet['!ref']};sheet['!cols']=Array.from({length:26},()=>({wch:24}));const book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,sheet,'Monitoramento');XLSX.writeFile(book,`Metrikon_Monitoramento_${new Date().toISOString().slice(0,10)}.xlsx`);setNotice(`${rows.length} instrumentos exportados com os filtros aplicados.`);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function openAccess(){setAccess(true);setAccessError('');setMembers([]);try{setMembers(mode==='cloud'?await minimal.members():[{userId:'demo-owner',email:'proprietario@exemplo.test',role:'owner',companyId:null,active:true}]);}catch(e){setAccessError((e as Error).message);}}
 async function saveMember(){setBusy(true);setAccessError('');try{if(mode==='cloud')setMembers(await minimal.member(memberEmail,memberRole,memberCompany||null,memberEnabled));else setMembers(all=>[...all.filter(m=>m.email!==memberEmail),{userId:crypto.randomUUID(),email:memberEmail,role:memberRole as Member['role'],companyId:memberCompany||null,active:memberEnabled}]);setMemberEmail('');}catch(e){setAccessError((e as Error).message);}finally{setBusy(false);}}
 const detailCertificate=detail?((detail as Instrument&{currentCertificate?:SimpleCertificate}).currentCertificate||history.find(r=>r.state==='aprovado')?.certificate):undefined;
 if(!mode)return <div className="login simple-login"><div className="login-panel"><img className="simple-login-logo" src="/metrikon-logo.png" alt="Logo Metrikon"/><h1>Metrikon</h1><p>Cadastro e monitoramento de instrumentos.</p><form onSubmit={e=>{e.preventDefault();login();}}><Field label="E-mail"><input type="email" autoComplete="username" required value={email} onChange={e=>setEmail(e.target.value)}/></Field><Field label="Senha"><input type="password" autoComplete="current-password" required minLength={8} value={password} onChange={e=>setPassword(e.target.value)}/></Field>{error&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status">{notice}</p>}<button className="primary full" disabled={busy}>{busy?'Entrando…':'Entrar'}</button><button type="button" className="text-button" disabled={busy||!email||password.length<8} onClick={signup}>Criar acesso</button></form><div className="login-separator" aria-hidden="true"><span>ou</span></div><button className="secondary full demo-entry" onClick={demonstration}>Explorar demonstração</button><small>Novos acessos precisam de confirmação do e-mail e liberação pelo proprietário.</small></div></div>;
 return <div className="minimal-app">
 <a className="skip-link" href="#main">Ir para o conteúdo</a>
 <header className="minimal-header">
  <div className="minimal-brand"><img src="/metrikon-logo.png" alt="Logo Metrikon"/><div><strong>Metrikon</strong><span>Controle de calibração</span></div></div>
  <div className="minimal-account"><span className="minimal-account-role"><ShieldCheck size={15} aria-hidden="true"/>{roleLabels[role]||role}</span>{can('manage_access')&&<button className="text-button" onClick={openAccess}>Acessos</button>}<button className="secondary" onClick={logout}>Sair</button></div>
 </header>
 {mode==='demo'&&<div className="minimal-demo"><span>Demonstração · dados fictícios</span><label>Perfil de demonstração <select value={role} onChange={e=>{setRole(e.target.value);setPermissions(permissionsFor(e.target.value));setEdit(null);setAccess(false);}}>{['owner','quality_admin','analyst','viewer'].map(v=><option key={v} value={v}>{roleLabels[v]}</option>)}</select></label></div>}
 <nav className="minimal-nav" aria-label="Espaço de trabalho">
  <button aria-current={tab==='cadastro'?'page':undefined} onClick={()=>navigate('cadastro')}><ClipboardList size={18} aria-hidden="true"/><span>Cadastro</span></button>
  <button aria-current={tab==='monitoramento'?'page':undefined} onClick={()=>navigate('monitoramento')}><Activity size={18} aria-hidden="true"/><span>Monitoramento</span></button>
 </nav>
 <main id="main" tabIndex={-1}>
  <div className="minimal-heading">
   <div><span className="minimal-kicker">Instrumentos e calibrações</span><h1>{tab==='cadastro'?'Cadastro':'Monitoramento'}</h1><p>{tab==='cadastro'?'Cadastre instrumentos e acompanhe o fluxo de aprovação.':'Acompanhe os vencimentos e mantenha os certificados atualizados.'}</p></div>
   {can('edit_registration')&&tab==='cadastro'&&<button className="primary" disabled={loading||busy} onClick={start}>Novo instrumento</button>}
  </div>
  {error&&<div className="notice danger" role="alert">{error}<button className="text-button" onClick={()=>setError('')}>Fechar aviso</button></div>}
  {notice&&<div className="notice success" role="status">{notice}</div>}
  <div className="minimal-metrics" aria-label="Resumo dos instrumentos">
   <button type="button" className="metric-card metric-card-primary" aria-label="Mostrar todos os instrumentos" aria-pressed={filter==='todos'} onClick={()=>applyMetric(tab,'todos')}><div className="metric-card-title"><span>Instrumentos</span><Gauge size={19} aria-hidden="true"/></div><strong>{workspace.metrics.total}</strong><small>Na sua base autorizada</small><ArrowRight className="metric-card-arrow" size={16} aria-hidden="true"/></button>
   <button type="button" className="metric-card metric-card-danger" aria-label="Mostrar instrumentos vencidos" aria-pressed={tab==='monitoramento'&&filter==='vencidos'} onClick={()=>applyMetric('monitoramento','vencidos')}><div className="metric-card-title"><span>Vencidos</span><AlertTriangle size={19} aria-hidden="true"/></div><strong>{workspace.metrics.expired}</strong><small>Precisam de atenção</small><ArrowRight className="metric-card-arrow" size={16} aria-hidden="true"/></button>
   <button type="button" className="metric-card metric-card-warning" aria-label={`Mostrar instrumentos a vencer nos próximos ${windowDays} dias`} aria-pressed={tab==='monitoramento'&&filter==='proximos'} onClick={()=>applyMetric('monitoramento','proximos')}><div className="metric-card-title"><span>A vencer</span><Clock size={19} aria-hidden="true"/></div><strong>{workspace.metrics.soon}</strong><small>Nos próximos {windowDays} dias</small><ArrowRight className="metric-card-arrow" size={16} aria-hidden="true"/></button>
   <button type="button" className="metric-card" aria-label="Mostrar cadastros aguardando aprovação" aria-pressed={tab==='cadastro'&&filter==='aprovacao'} onClick={()=>applyMetric('cadastro','aprovacao')}><div className="metric-card-title"><span>Aguardando aprovação</span><CheckCircle2 size={19} aria-hidden="true"/></div><strong>{workspace.metrics.pending}</strong><small>Revisão pelo responsável</small><ArrowRight className="metric-card-arrow" size={16} aria-hidden="true"/></button>
  </div>
  <section className="panel minimal-list">
   <header className="minimal-list-head"><div><h2>{tab==='cadastro'?'Cadastros e aprovações':'Seus instrumentos'}</h2><p>{tab==='cadastro'?'Prepare, consulte e acompanhe as fichas dos instrumentos.':'Abra a ficha para consultar os dados e o histórico.'}</p></div><div className="minimal-list-actions"><button className="secondary minimal-export" disabled={busy||loading} onClick={exportList}><Download size={16} aria-hidden="true"/>Exportar lista</button><button className="icon-button minimal-refresh" aria-label="Atualizar lista" title="Atualizar lista" disabled={loading} onClick={()=>setRevision(v=>v+1)}><RefreshCw size={17} aria-hidden="true"/></button></div></header>
   <div className="minimal-filters">
    <Field label="Pesquisar instrumento"><input type="search" placeholder="Número LI, série, equipamento ou local" value={search} onChange={e=>setSearch(e.target.value)}/></Field>
    <Field label="Mostrar"><select value={filter} onChange={e=>{setFilter(e.target.value);setPage(0);}}><option value="todos">Todos os instrumentos</option>{tab==='cadastro'?<option value="aprovacao">Aguardando aprovação</option>:<><option value="vencidos">Vencidos</option><option value="proximos">Próximos do vencimento</option><option value="sem_data">Sem vencimento informado</option></>}</select></Field>
    {tab==='monitoramento'&&<Field label="Próximos em até (dias)"><input type="number" min={1} max={365} value={windowDays} onChange={e=>{const value=Number(e.target.value);if(value>=1&&value<=365){setWindowDays(value);setPage(0);}}}/></Field>}
   </div>
   <div className="minimal-filter-summary"><span><Activity size={14} aria-hidden="true"/>{filter==='todos'?'Todos os instrumentos':filter==='vencidos'?'Vencidos':filter==='proximos'?'Próximos do vencimento':filter==='sem_data'?'Sem vencimento informado':'Aguardando aprovação'}</span><strong>{workspace.total}</strong></div>
   {loading&&<p className="minimal-loading" role="status">Carregando instrumentos…</p>}
   {!loading&&!workspace.items.length&&<Empty>Nenhum instrumento encontrado.</Empty>}
   <div className="minimal-rows">{workspace.items.map(({instrument:i,openRegistration:r})=>{const status=monitoringStatus(i,windowDays);return <article className="minimal-row" key={i.id}><div className="minimal-row-title"><button className="row-title" onClick={()=>openDetail(i)}>{i.liNumber||i.serial}</button><h2>{i.criticality}</h2><p>Série {i.serial||'—'} <span aria-hidden="true">·</span> {i.location||'Local não informado'}</p></div><div className="minimal-row-dates"><div className="minimal-row-status"><Badge>{status}</Badge><span>{deadlineCopy(i)}</span>{r&&<Badge>{r.state}</Badge>}</div><div className="minimal-row-date-values"><span>Calibração <strong>{fmt(i.lastControl)}</strong></span><span>Vencimento <strong>{fmt(i.nextControl)}</strong></span></div></div><div className="minimal-row-actions"><button className="secondary" onClick={()=>openDetail(i)}>Ver ficha</button>{r?.state==='aguardando aprovação'?can('review_registration')&&<button className="primary" disabled={busy} onClick={()=>setEdit(r)}>Revisar cadastro</button>:can('edit_registration')&&<button className="primary" disabled={busy} onClick={()=>update(i,r)}>{r?'Continuar cadastro':tab==='monitoramento'?'Atualizar certificado':'Editar instrumento'}</button>}</div></article>;})}</div>
   <footer className="pagination"><span>{workspace.total} encontrados</span><div><button className="secondary" disabled={page===0||loading} onClick={()=>setPage(v=>v-1)}>Anterior</button><span>Página {page+1}</span><button className="secondary" disabled={(page+1)*50>=workspace.total||loading} onClick={()=>setPage(v=>v+1)}>Próxima</button></div></footer>
  </section>
 </main>
 <footer className="minimal-footer">Metrikon · Cadastro e monitoramento · {session?.user.email||'Demonstração'}</footer>
 {edit&&<Modal wide title={edit.state==='aguardando aprovação'?'Revisar cadastro':isRenewal(edit)?'Atualizar calibração':edit.version?'Continuar cadastro':'Cadastrar instrumento'} onClose={()=>{if(!busy)setEdit(null);}}><SimpleRegistrationForm key={edit.id} initial={edit} li={li} busy={busy} reviewOnly={edit.state==='aguardando aprovação'} onSave={save} onReview={review} onOpen={openFile} onCancel={()=>setEdit(null)}/></Modal>}
 {detail&&<Modal wide title="Ficha do instrumento" onClose={()=>setDetail(null)}>
  <div className="detail-body">
   <div className="detail-hero">
    <div><span className="minimal-kicker">Instrumento</span><h3>{detail.criticality}</h3><p>{detail.liNumber||'LI não informada'} · Série {detail.serial||'—'}</p></div>
    <div className="detail-hero-status"><Badge>{monitoringStatus(detail,windowDays)}</Badge><strong>{deadlineCopy(detail)}</strong></div>
   </div>
   <section className="detail-section">
    <header><h3>Identificação</h3></header>
    <dl className="detail-grid">{[['Número LI',detail.liNumber],['Linha LI',detail.liSource?.row],['Equipamento',detail.criticality],['Código de série / identificação',detail.serial],['Modelo',detail.model],['Status do cadastro',detail.registrationStatus]].map(([label,value])=><div key={String(label)}><dt>{label}</dt><dd>{value||'—'}</dd></div>)}</dl>
   </section>
   <section className="detail-section">
    <header><h3>Localização e uso</h3></header>
    <dl className="detail-grid">{[['Obra',detail.workSite],['Local de uso',detail.location],['Processo',detail.process],['Área/Setor responsável pela calibração do equipamento',detail.calibrationResponsibleArea],['Equipamento de empresa contratada?',detail.contractorEquipment],['Empresa contratada',detail.contractorEquipment==='sim'?detail.contractorCompanyName||'—':'Não se aplica']].map(([label,value])=><div key={String(label)}><dt>{label}</dt><dd>{value||'—'}</dd></div>)}</dl>
   </section>
   <section className="detail-section">
    <header><h3>Parâmetros</h3></header>
    <dl className="detail-grid">{[['Faixa de medição',detail.measurementRange],['Faixa de utilização',detail.usageRange],['Valor da divisão de verificação do equipamento',detail.verificationDivision],['Intervalo de calibrações (em meses)',detail.periodicityMonths]].map(([label,value])=><div key={String(label)}><dt>{label}</dt><dd>{value||'—'}</dd></div>)}</dl>
   </section>
   <section className="detail-section detail-current">
    <header><div><span className="minimal-kicker">Situação atual</span><h3>Calibração vigente</h3></div><Badge>{monitoringStatus(detail,windowDays)}</Badge></header>
    <dl className="detail-grid">{[['Certificado',detailCertificate?.certificateNumber],['Laboratório',detailCertificate?.laboratory],['Data da calibração',fmt(detail.lastControl)],['Vencimento',fmt(detail.nextControl)],['Situação do equipamento',detail.operationalStatus],['Resultado',detailCertificate?evaluateSimple(detailCertificate).status:'—']].map(([label,value])=><div key={String(label)}><dt>{label}</dt><dd>{value||'—'}</dd></div>)}</dl>
   </section>
   <section className="detail-section history-section">
    <header><div><span className="minimal-kicker">Rastreabilidade</span><h3>Histórico de certificados</h3></div></header>
    {historyLoading&&<p className="minimal-loading" role="status">Carregando histórico…</p>}
    {!historyLoading&&!history.length&&!legacy.length&&<Empty>Sem certificado aprovado.</Empty>}
    <div className="certificate-timeline">
     {history.map(r=><article className="minimal-history" key={r.id}><div className="history-marker" aria-hidden="true"/><div className="history-card"><header><div><strong>{r.certificate.certificateNumber||'Certificado pendente'}</strong><small>Versão {r.version} · {fmt(r.certificate.date)} → {fmt(r.certificate.nextDate)}</small></div><Badge>{r.state}</Badge></header><dl className="history-grid"><div><dt>Laboratório</dt><dd>{r.certificate.laboratory||'—'}</dd></div><div><dt>Situação</dt><dd>{r.certificate.decision||'—'}</dd></div><div><dt>Resultado</dt><dd>{r.quantitative.total||'—'} ≤ {r.certificate.processTolerance||'—'} · {r.quantitative.status}</dd></div><div><dt>Aceitação</dt><dd>{r.certificate.calibrationAccepted||'—'}{r.certificate.acceptedWithRestriction==='sim'?' · com restrição':''}</dd></div></dl>{r.certificate.laboratoryAccredited==='não'&&<p>Padrões validados quanto à rastreabilidade e validade: {r.certificate.standardsValidation||'Não informado'}</p>}{r.certificate.acceptedWithRestriction==='sim'&&<p><strong>Restrição:</strong> {r.certificate.restrictionText||'Não informada'}</p>}{r.instrument.contractorEquipment==='sim'&&<p>Empresa contratada: {r.instrument.contractorCompanyName||'Não informada'}</p>}{r.reviewedAt&&<small>Revisão: {new Date(r.reviewedAt).toLocaleString('pt-BR',{timeZone:'America/Recife'})} · Responsável: {r.reviewedName||'Responsável autorizado'}</small>}{r.reviewNotes&&<p>{r.reviewNotes}</p>}{r.certificate.attachmentPath&&<button className="text-button" onClick={()=>openFile(r.certificate.attachmentPath)}>Abrir certificado {r.certificate.certificateNumber}</button>}</div></article>)}
     {legacy.map(e=><article key={e.id} className="minimal-history legacy-history"><div className="history-marker" aria-hidden="true"/><div className="history-card"><header><div><strong>{e.certificateNumber||'Certificado anterior'}</strong><small>Histórico anterior · {fmt(e.date)} → {fmt(e.nextDate)}</small></div><Badge>{e.workflow}</Badge></header><p>{e.laboratory||'Laboratório não informado'}</p>{e.attachmentPath&&<button className="text-button" onClick={()=>openFile(e.attachmentPath)}>Abrir certificado {e.certificateNumber}</button>}</div></article>)}
    </div>
   </section>
  </div>
  <footer className="wizard-footer"><button className="secondary" onClick={()=>setDetail(null)}>Fechar ficha</button></footer>
 </Modal>}
 {access&&can('manage_access')&&<Modal title="Perfis de acesso" onClose={()=>{if(!busy)setAccess(false);}}><div className="wizard-body"><p>Proprietário gerencia acessos; Responsável aprova ou devolve; Cadastro preenche e envia; Consulta acompanha os instrumentos.</p><form onSubmit={e=>{e.preventDefault();saveMember();}}><Field label="E-mail do usuário"><input required type="email" value={memberEmail} onChange={e=>setMemberEmail(e.target.value)}/></Field><Field label="Perfil"><select value={memberRole} onChange={e=>setMemberRole(e.target.value)}>{['quality_admin','analyst','viewer'].map(v=><option key={v} value={v}>{roleLabels[v]}</option>)}</select></Field><Field label="Acesso à empresa"><select value={memberCompany} onChange={e=>setMemberCompany(e.target.value)}><option value="">Todas as empresas autorizadas do espaço</option>{companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="Acesso"><select value={memberEnabled?'ativo':'inativo'} onChange={e=>setMemberEnabled(e.target.value==='ativo')}><option value="ativo">Ativo</option><option value="inativo">Inativo</option></select></Field><button className="primary" disabled={busy}>Salvar perfil</button></form><p className="muted">O usuário cria e confirma seu acesso na tela inicial. O proprietário então libera o perfil pelo e-mail. Nenhum perfil é concedido automaticamente.</p>{accessError&&<p role="alert" className="error">{accessError}</p>}<h3>Usuários vinculados</h3>{members.map(m=><article className="minimal-member" key={m.userId}><strong>{m.email}</strong><small>{roleLabels[m.role]} · {m.active?'ativo':'inativo'} · {m.companyId?companies.find(c=>c.id===m.companyId)?.name:'Todas as empresas'}</small>{m.role!=='owner'&&<button className="text-button" onClick={()=>{setMemberEmail(m.email);setMemberRole(m.role);setMemberCompany(m.companyId||'');setMemberEnabled(m.active);}}>Editar perfil</button>}</article>)}</div></Modal>}
 </div>;
}
